### ISSUE TITLE
Hardening TypedArray

### ISSUE THREAD

**Issue by kriskowal** [endojs/endo#1029]
Currently, freezing a TypedArray throws, so harden throws. But

- typed arrays really ought to be directly marshalable for ergonomic reasons. The alternative is to wrap all typedarrays in a Blob wrapper of some kind
- hardening a Map or Set is morally equivalent to preventing extensions and making all properties non-writable on a TypedArray

Making a special case for typed array in harden poses a couple challenges:

Differentiating a typed array appears to require try/catch, and try/catch in a hot loop is expensive. try/catch deoptimizes the entire surrounding function, so the usual trick to making it go fast is to have an intermediate function on the stack between two optimizable functions. We could amortize the cost by making a freeze queue and a trampoline that may resume flushing the queue if freeze throws and verifying the type of the typed array does not.

The current best idea for inducing the isTypedArray check is:

```js
Reflect.apply(Object.getOwnPropertyDescriptor(Object.getPrototypeOf(Uint8Array.prototype), Symbol.toStringTag).get, target, [])
```

as of 2022-01-28, by @mhofman

**Comment by kriskowal** [comment]
Blocks https://github.com/endojs/endo/pull/1028

**Comment by mhofman** [comment]
> try/catch deoptimizes the entire surrounding function

I hear that's no longer the case in some engines

As discussed, we should still attempt to freeze the TypedArray as deeply as possible. That would look like:
- Object.seal
- getOwnProperties, any non-index and index higher than the length, update desc to non-writable (which is allowed on non-configurable props)

**Comment by erights** [comment]
> Object.seal (prevents extensions including making proto immutable, and make all existing props non-configurable)

Given that we take the other steps you describe, `preventExtensions` should be equivalent. There should be no observable difference. Nevertheless, for defense in depth, I would find `seal` acceptable too if you prefer that.

**Comment by mhofman** [comment]
Ah right, since the real index own props are non-configurable already, `preventExtensions` should be strictly equivalent to `seal` if we update all the descriptions of the other properties to non-configurable non-writable!

**Comment by erights** [comment]
Re trampoline

Note that `harden` is already queue-driven breadth-first fifo rather than stack-driven depth-first lifo, so this may be easier than I first expected. When I first understood it, it seemed like overkill for a problem we don't know we have. But we do have some experience showing we're sensitive to the speed of `harden` in particular, so this optimization may not be premature.

**Comment by mhofman** [comment]
Btw, this means a proxy of TypedArray cannot be hardened, since we'd be doing a brand check, and there's no way for a proxy to pretend being a TypedArray.

**Comment by erights** [comment]
> Btw, this means a proxy of TypedArray cannot be hardened, since we'd be doing a brand check, and there's no way for a proxy to pretend being a TypedArray.

Good catch! Uh oh. Fixing this will be complicated:

The proxy doesn't have to pass the brand check. The proxy has to pass `harden`, and therefore `isFrozen`, while still acting *adequately* like a typed array. By *adequately*, I mean that it does SET and PUT of indexed properties "correctly". But it does not need to pretend these are own properties. It can pretend to have inherited the indexed properties. I'd guess less than 1% of TypeArray code will care about this loss of fidelity.

Yuck! But I think it would work.

**Comment by mhofman** [comment]
Oh yeah, the pesky workaround that `get`, `set` and `has` traps can do whatever they want for non-own properties, and that there is no checks that these props exists somewhere on the prototype chain, so can actually be handled by the exotic proxy object...
