### ISSUE TITLE
Seeing "impossible" error on master for typed array tests

### ISSUE THREAD

**Issue by erights** [endojs/endo#1045]
A `yarn test` in endojs/endo master in `packages/ses`. Looks like a `configurable: true` somehow snuck in there for an indexed property on a typed array, which should be impossible. Or I'm reading the test wrong.

```
  make-hardener › harden typed arrays

  Difference:

    {
  -   configurable: false,
  +   configurable: true,
      enumerable: true,
      value: 0n,
      writable: true,
    }
```
and
```
  make-hardener › harden typed arrays and their expandos

  Difference:

    {
  -   configurable: false,
  +   configurable: true,
      enumerable: true,
      value: 0,
      writable: true,
    }
```

**Comment by kriskowal** [comment]
@erights What version of Node.js are you using?

**Comment by kriskowal** [comment]
You must be using 16. There’s a behavior difference in 14 and 12 that is probably explained by a V8 bugfix. I can for now relax the test to not check this property.

**Comment by erights** [comment]
I'm using Node v16.13.1
