### ISSUE TITLE
Drop Node.js 12 support in CI

### ISSUE THREAD

**Issue by kriskowal** [endojs/endo#1046]
Node.js 12 is becoming a burden. We need to drop it to upgrade TypeScript and ESLint. This would also give us an opportunity to drop some hacks around CommonJS named exports. This would also let us drop a work-around for old V8 generator function behavior in streams. Neither of those changes need to be done to close this issue. We need:

- [x] Remove 12 from CI matrixes.
- [ ] Update Node.js `engines` properties in `package.json` where applicable. Soft requirement.
- [ ] NEWS.md entries.
- [ ] This might be a whole-repo breaking change. Dropping an old Node.js version is breaking at least in principle.

**Comment by mhofman** [comment]
No longer necessary for TS 4.5 update so reassigning.

**Comment by kriskowal** [comment]
@Tartuffo No, this is orthogonal maintenance. The longer we put this off, the more time we waste on compatibility.

**Comment by Tartuffo** [comment]
@kriskowal Let me put this another way - do you plan to do this in the Mainnet-1 timeframe?  If so, the only way to track that you are going to spend time on this is to put it into the "Mainnet 1" release.

**Comment by kriskowal** [comment]
Roger, all debts paid in MN-1 are MN-1 debts. This somewhat changes how I classified issues in backlog grooming, so we’ll need to move some things from product backlog to the MN-1 column.

**Comment by Tartuffo** [comment]
Yes, please do!

**Comment by rekmarks** [comment]
As of today's date, even Node 16 is EOL. Is there any appetite for dropping all Node versions <18?
<img width="757" alt="image" src="https://github.com/endojs/endo/assets/25517051/ed33da74-fd38-4b87-9719-dbf13460e170">

ref: https://nodejs.org/en/about/previous-releases

**Comment by kriskowal** [comment]
I would be open to entertaining a change that generally shifted our testing regimen to 18 and dropped support for 16. I would also like to begin a discipline of updating the `engines` field for `ses` at least to have both a minimum and maximum version.

**Comment by kriskowal** [comment]
We definitely need to be that explicit for `ses`, but perhaps can be more open for others. I’m fine with forcing us to expressly opt in for new node versions. It does mean we become instantly irrelevant if we stop working, but that’s the safe option.

**Comment by mhofman** [comment]
Apparently in most sane package managers the `engines` field is advisory only anyway
