### ISSUE TITLE
Can't use __evadeImportExpressionTest__ 

### ISSUE THREAD

**Issue by naugtur** [endojs/endo#1063]
Having found:
- https://github.com/endojs/endo/issues/498
- https://github.com/endojs/endo/blob/master/packages/ses/error-codes/SES_IMPORT_REJECTED.md

I decided to make a test covering that case.

```js
 const application = await loadLocation(read, fixture, {
    __evadeImportExpressionTest__: true,
  });
  await application.import({
    __evadeImportExpressionTest__: true,
  });
```
Unfortunately, none of these worked.

So I traced the callstack of my test to where the option could be passed to `compartment.evaluate`

The transform to evade issues with import expressions is added in [compartment-evaluate.js:88](https://github.com/endojs/endo/blob/677141ca56d0749c382ee68d344d1500851da400/packages/ses/src/compartment-evaluate.js#L88) where the only reference to the context of the compartment is privateFields (as compartmentFields) which cover many fields, but not options. [compartment-shim.js:304](https://github.com/endojs/endo/blob/806521e94c8ba90617344760b3a80412b7a83ab6/packages/ses/src/compartment-shim.js#L304)

----
Problems:

1. There's no way to drill down the option from the code that calls `loadLocation` and it seems to me it'd be best if it could be decided there instead of inside Endo's compartment-mapper code.
2. An attempt to pass it directly inside parse-cjs.js works if you ignore typescript error - too many arguments: [index.d.ts:219](https://github.com/endojs/endo/blob/naugtur-failing-tests-for-cjs-compat/node_modules/ses/index.d.ts#L219)

```js
const application = await loadLocation(read, fixture);
 await application.import({ OPTIONS });
```
OPTIONS can potentially drill down to be passed to Compartment constructor and then over to evaluate. There's no direct path from application.import to evaluate that wouldn't have to jump through codebase that shouldn't be bothered with passing down those options.

**Comment by kriskowal** [comment]
Have you considered `application['import'](x)` instead of evading dynamic import censorship? Dynamic import allows an attacker to load arbitrary modules of the host environment.

**Comment by naugtur** [comment]
TBH, I just wanted to get the feature working assuming the dynamic import is not in my code, but in a codebase I'm trying to make work (like some of the examples from #498)

**Comment by Tartuffo** [comment]
@kriskowal Please triage

**Comment by naugtur** [comment]
I no longer think using __evadeImportExpressionTest__ is a good idea, but we can always reopen ;)

**Comment by erights** [comment]
> I no longer think using evadeImportExpressionTest is a good idea, but we can always reopen ;)

Why? No objection. Just curious.

**Comment by naugtur** [comment]
Initially I didn't understand why import are an issue. Now I know they're not handled (yet?) 
Dynamic imports could be handled in cjs if we applied the babel transform there (with some changes I suppose) 
Anyway, being able to switch the import expression test off doesn't seem to be what we'd need in a normal usecase.
I'd put the effort in ignoring/removing `import` in comments, which often triggers the test.
