### ISSUE TITLE
Compartment mapper should interpret package `module` as implicit `type: module`

### ISSUE THREAD

**Issue by kriskowal** [endojs/endo#1110]
Currently, the compartment mapper makes an exception for the `"module"` property in `package.json`, marking just that one file as an ESM, but leaving the rest of the package alone. The correct behavior would be to infer that the entire package is ESM and that the one given file corresponds to `"main"`.

**Comment by kriskowal** [comment]
cc @michaelfig For identifying this issue.

**Comment by naugtur** [comment]
This might explain one issue I saw in e2e tests
