### ISSUE TITLE
Test harness for types

### ISSUE THREAD

**Issue by turadg** [endojs/endo#1118]
## What is the Problem Being Solved?

Many of our type are "best effort" and inaccurate. `any` abounds. Having tests of our types per se would help:

1. Prevent regressions. While we _improve_ the types in some places, they may regress in others if we don't have checks.
2. Document known problems. Bad type defs lead to yak shaving, where fixing one little thing branches into many others. If we had a list of known issues (documented in tests) then when those errors were encountered there could be some documentation as to why they're in that state, saving yaks.
3. Increase velocity while debugging types. Being able to set up explicit test cases and a watcher shrinks the test cycle.

## Description of the Design

Add https://github.com/SamVerschueren/tsd to CI

Adapt https://github.com/endojs/endo/tree/master/packages/ses-types-test 

TBD whether to have the test in each package or at the repo level.

## Security Considerations
n/a, static analysis

## Test Plan

New part of CI linting.

**Comment by michaelfig** [comment]
`tsd` looks nice.  I'd also suggest adopting `endo/packages/eventual-send/test/test-types.js`, if useful.  It both tests the types and tries executing code to validate the dynamic behaviour.

**Comment by turadg** [comment]
> I'd also suggest adopting endo/packages/eventual-send/test/test-types.js, if useful. It both tests the types and tries executing code to validate the dynamic behaviour.

That was useful, thanks. I moved it over forgetting your comment and assuming the runtime parts were tested elsewhere. I do think we should separate testing _runtime_ types from static types but I'm happy to add back anything no longer tested.

**Comment by turadg** [comment]
> we should separate testing runtime types from static types

Thought a little more about this and not so sure. Maybe it would be better to keep them together in one file. Tsd's type utils will work in any `.ts` file. I think I'd just need to change the `test-types.js` to `.ts`. Oh but then we'd have to configure Ava to support .ts files. That would be worthwhile IMO but it's a larger matter for this repo.

**Comment by mhofman** [comment]
I would be in favor of keeping static type checks separate. You can cast and test a lot more things if you don't need to also make it runtime valid (aka build up the correct state).
