### ISSUE TITLE
Allow packages to use import self-references

### ISSUE THREAD

**Issue by mhofman** [endojs/endo#1121]
If a `package.json` contains an `"exports"` field, its modules are allowed to use [self-references](https://nodejs.org/api/packages.html#packages_self_referencing_a_package_using_its_name) (using its own package name in import identifiers) to import modules that then go through the conditional export resolution.

We need to support this for ecosystem compatibility.

**Comment by kriskowal** [comment]
Reflexive imports are already implemented, but https://github.com/endojs/endo/pull/1114 suffered from a missing `default` condition. https://github.com/endojs/endo/blob/master/packages/compartment-mapper/src/node-modules.js#L445-L446
