### ISSUE TITLE
SES possible HTMLcomment error from valid JS syntax

### ISSUE THREAD

**Issue by naugtur** [endojs/endo#1138]
```
Possible HTML comment rejected at file:///.../node_modules/ethjs-unit/node_modules/bn.js/lib/bn.js:2523. (SES_HTML_COMMENT_REJECTED)
```

bn.js: 
```js
        while (i-- > 0) {
          if (A.isOdd() || B.isOdd()) {
```

there's a space between `--` and `>` so it should be fine (as per docs)

**Comment by naugtur** [comment]
nope, it's fine, side-effect of a transform.

**Comment by koonopek** [comment]
Hi, I'm having similar issue, could you describe how you solve it in your case @naugtur? Or what caused it

**Comment by naugtur** [comment]
One misguided transform removed some whitespace and -- > became -->

I'm now using a transform that's not doing that.
See endo-e2e-tests/test-imports
Look for scaffold file.
