### ISSUE TITLE
errorTaming: 'unsafe' does not work on Firefox

### ISSUE THREAD

**Issue by Jack-Works** [endojs/endo#1165]
![image](https://user-images.githubusercontent.com/5390719/163918939-56e1beaa-6652-4b49-82ab-e3642f6691cc.png)

Test code:

```js
await import('https://cdn.jsdelivr.net/npm/ses@0.15.15/dist/lockdown.mjs')
lockdown({ errorTaming: 'unsafe' })
new Error().stack.toString()
```

**Comment by erights** [comment]
Hi @Jack-Works the bug is in my code. I think I know what to do and have assigned it to myself.

Thanks for the report!
