### ISSUE TITLE
Compartment mapper: Collect garbage compartments

### ISSUE THREAD

**Issue by kriskowal** [endojs/endo#1173]
Keywords: mark and sweep, tree shaking

The `compartmentMapFromNodeModules` algorithm produces a compartment map that contains a compartment for every physical package.json that it discovers. The `makeArchive` algorithm preserves all of this structure but only retains physical modules if they’re reachable from the entrypoint. Often, many of the compartments are superfluous. We should add a garbage collector that removes any compartment that is not on the resolution path to a retained module.

**Comment by Tartuffo** [comment]
@kriskowal please close if done.

**Comment by kriskowal** [comment]
Fixed in https://github.com/endojs/endo/pull/1174
