### ISSUE TITLE
`bundleSource` emits a bundle when entrypoint does not exist

### ISSUE THREAD

**Issue by kriskowal** [endojs/endo#1206]
The following program should throw an error because bogus.js does not exist. Instead, it generates a bundle.

```js
import '@endo/init';
import bundleSource from '@endo/bundle-source';
(async () => {
  const bundle = await bundleSource(new URL('bogus.js', import.meta.url).pathname);
  console.log(bundle);
})();
```

**Comment by warner** [comment]
BTW the "empty" bundle this creates has `bundle.endoZipBase64.length === 11320`, so there is enough header/index material to make a nontrivial zip file, but still too incomplete to be importable.

**Comment by kriskowal** [comment]
Coming soon to a release and integration near you.
