### ISSUE TITLE
@endo/init + styled components throws

### ISSUE THREAD

**Issue by dckc** [endojs/endo#1209]
## Steps To Reproduce

> Just try yarn start and you should be able to see the error on the console.

https://github.com/ecovirtual/endo-react-styled-components

_raised on behalf of @ecovirtual ; ref
https://discord.com/channels/585576150827532298/755164562952683540/984023587314868234

**Comment by mhofman** [comment]
Duplicate of #1208

**Comment by dckc** [comment]
oops!
