### ISSUE TITLE
Consider "unbinding" `E` methods

### ISSUE THREAD

**Issue by mhofman** [endojs/endo#1253]
The implementation of the `E` proxy allows to use the methods as free function as it implicitly binds them, preventing future changes that may require to revert this behavior.

https://github.com/endojs/endo/blob/fe9c78414eab5d1bce73cdb16e1455c1c4307e98/packages/eventual-send/src/E.js#L33

A similar issue arose in the [agoric-sdk for local kind representatives](https://github.com/Agoric/agoric-sdk/pull/5970) which is planned to switch to a more "class" based implementation which is incompatible with bound methods.

While this would be a breaking change to the `E` proxies as some code currently relies on this auto-binding behavior, we could add a check in the E proxy handlers to disallow this bound usage.

```js
    get(_target, p, receiver) {
      return harden({
        [p](...args) {
          assert(this === receiver);
          return HandledPromise.applyMethod(x, p, args);
        },
      }[p]);
    },
```

**Comment by mhofman** [comment]
Based on a quick grep, I found only a few offenders in agoric-sdk: https://github.com/Agoric/agoric-sdk/commit/ab3b5900fd0845b9ed8081f61cadf81704891ba2

**Comment by erights** [comment]
Please do this, together with https://github.com/Agoric/agoric-sdk/commit/ab3b5900fd0845b9ed8081f61cadf81704891ba2

Assigning to you ;)

Thanks!
