### ISSUE TITLE
Node.js adds a property called `domain` to promises

### ISSUE THREAD

**Issue by katelynsills** [endojs/endo#126]
Mark and I noticed that Node.js adds a property called `domain` to promises while running something from a REPL in SwingSet. 

Mark says that `domain` leads to all sorts of objects whose semantics we haven't inspected for safety. This is an authority leak. If SES can't remove the domain property from all promises before the promise is exposed to user code, then this is a severe authority leak for SES as run on Node.js. Fortunately it seems to only be a problem when code is run from a REPL. 

[edit 2020-09-15 @kriskowal]

SES will not be secure on Node.js until we have the means to disable `domains`. We must work with the Node.js project to reveal a command-line flag or the moral equivalent.

**Comment by kriskowal** [comment]
A tip from @dominictarr suggests it is possible to disable domains by defining `domain` as a non-configurable property of the `process` global, as that would prevent `require("domain")` from initializing. In some circumstances, we can also check whether `domain` initialized before we put our trap in place.

```js
if (typeof process === 'object' && process !== null) {
  // Prevents domains from initializing:
  Object.defineProperty(process, 'domain', {value: null, configurable: false, writable: false, enumerable: false});
  if (typeof require === 'function') {
    let domainsInitializedAlready = false;
    try {
      require('domain')
      domainsInitializedAlready = true;
    } catch {
      // We expect an initialization error.
    }
    if (domainsInitializedAlready) {
      throw new Error(`SES cannot guarantee containment if Node.js domains have already been initialized`);
    }
  }
}
```

This covers CommonJS only. We might be able to do the same with dynamic import, but only asynchronously, and we can’t feature-detect ESM with `typeof`.

**Comment by kriskowal** [comment]
Now without caveats:

```js
if (typeof process === 'object' && process !== null) {
  // Check whether domains were initialized:
  const domainDescriptor = Object.getOwnPropertyDescriptor(process, 'domain');
  if (domainDescriptor !== undefined && domainDescriptor.get !== undefined) {
    throw new Error(`SES cannot guarantee containment if Node.js domains have been installed`);
  }
  // Prevents domains from initializing:
  Object.defineProperty(process, 'domain', {value: null, configurable: false, writable: false, enumerable: false});
}
```

**Comment by mhofman** [comment]
An alternative in case we want t  allow `import 'domain'`, but prevent domain usage:
- To prevent domains from being created: Add a `Domain.prototype.on` function which throws (normally inherited from `EventEmitter.prototype`), and harden `Domain`
- For good measure to make sure domains can't be switched if one was created: `Object.freeze(domain._stack)`
- To do all this while preventing modification to the `process` global: Replace `globalThis.process` with a proxy which traps a few things (like define `domain`, set `setUncaughtExceptionCaptureCallback`, add `on` which ignores new listeners ?), `import 'domain'`, restore `globalThis.process` and eventually restore `EventEmitter.prototype.emit` for good measure, event though it should be inert at that point.

**Comment by kriskowal** [comment]
One of the implicit albeit soft requirements is to avoid coupling SES to any particular module system. Currently, the same source works in a browser script, CJS, and ESM, since it’s just presenting its API as mutations to the global scope. This keeps the build system small and avoids initializing anything it doesn’t need.

I’m going to present a PR with the snippet above.
