### ISSUE TITLE
Uncaught ReferenceError: harden is not defined

### ISSUE THREAD

**Issue by Jack-Works** [endojs/endo#1281]
This is wrong. It crashes in our environment.

![image](https://user-images.githubusercontent.com/5390719/189535478-707a6938-c148-40a9-8537-398d22280b1c.png)

Because when this function is called, there is no `harden` defined yet.

_Originally posted by @Jack-Works in https://github.com/endojs/endo/pull/1241#discussion_r967845817_

**Comment by Jack-Works** [comment]
hello 👀

**Comment by kriskowal** [comment]
👋 I’m working on this. Thanks for your patience.

I found that I need to bypass all function repairs if eval is disabled, but I don’t feel good about doing that without also verifying that the other intrinsic evaluators are inert. So, I’ve done that, and now I’m bolstering the no-eval emulation environment to make all the evaluators inert, not just `eval` proper. So at this point, I’m improving the tests.

**Comment by plusminushalf** [comment]
It crashes for us as well, do we have any update on this issue?

Environment: Chrome extension, Manifest version v3, loading SES in an iframe in one of the HTML pages with the page being part of the v3 sandbox environment.

**Comment by plusminushalf** [comment]
This isn't an issue with version 0.12.4 but rather with version 0.18.0

**Comment by damianofalcioni** [comment]
Sorry to reopen this issue but the same error still occur in Node for latest SES from npm (1.9.0):
```
import 'ses';

const compartment = new Compartment({
  globals: {
    print: harden(console.log)
  },
  __options__: true
});
compartment.evaluate('print("Hello World");');
```
Return:

```
file:///...
    print: harden(console.log)
           ^

ReferenceError: harden is not defined
    at file:///....
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5)

Node.js v20.16.0
```

**Comment by kriskowal** [comment]
@damianofalcioni In the above snippet, call `lockdown` after importing `ses` and it will expose `harden`. Using `harden` before lockdown would prevent subsequent `lockdown` from succeeding and using `harden` without `lockdown` and `Compartment` provides no guarantee of isolation.

**Comment by damianofalcioni** [comment]
Thanks, that work!
As a suggestion, please fix the readme code (https://github.com/endojs/endo/tree/master/packages/ses#compartment) that propose this sample without lockdown()
