### ISSUE TITLE
Deterministic script bundle

### ISSUE THREAD

**Issue by kriskowal** [endojs/endo#1294]
Per https://github.com/Agoric/agoric-sdk/issues/6298, Agoric needs a bundle format that like `endoZipBase64` is deterministic but like `getExport`, is a single script. The compartment mapper currently has a `bundle.js` tool that is suitable for generating a single script for SES, but is not yet adequate for the Agoric kernel.

To close that gap, we need to generalize `bundle.js` so it can shorten aliases between compartments. That would allow us to build a deterministic bundle for the kernel. The bundler would still be limited to ESM and would not support top-level-await.

I’m proposing the new bundle format be exposed through `@endo/bundle-source` and `@endo/import-bundle` with the name `endoScript`. That would leave open room for `endoNestedEvaluate` for a more debugger friendly version that uses `eval` for each module (which would not be suitable for SES in no-eval environments).

**Comment by michaelfig** [comment]
#6298 is solved for `getExports`, so closing this issue as not strictly necessary.
