### ISSUE TITLE
TypedArrays are not passable, but not because they need to be hardened

### ISSUE THREAD

**Issue by kriskowal** [endojs/endo#1326]
At time of writing, attempting to send a message that contains a `TypedArray` produces an error to the effect `Cannot pass non-frozen objects like (an object). Use harden()`. This is confusing because `harden` has a special case for `TypedArrays`, the result of which is that the TypedArray becomes non-extensible, all its properties become non-configurable, but its content remains mutable, much like a hardened `Map`. But, like a `Map`, it should not be passable because of that content-mutability.

The expected behavior is that sending a message containing a TypedArray should produce a rejection with an Error that states that TypedArrays are not passable.

- [Alternate hardening behavior for TypedArrays](https://github.com/endojs/endo/blob/ab31d51fc2df0355b45da8bbeff892c45d81c98a/packages/ses/src/make-hardener.js#L76-L110)
- [Exceptionally non-obvious defensive brand-check for typed arrays](https://github.com/endojs/endo/blob/ab31d51fc2df0355b45da8bbeff892c45d81c98a/packages/ses/src/make-hardener.js#L58-L74)

We might avoid duplicating the brand check by producing an `isHardened` global that generalizes `isFrozen`. We’ve avoided this in the past because most places where you’d reach for `isHardened` are places that would be better served by calling `harden` regardless of whether it was previously hardened.

**Comment by kriskowal** [comment]
Assigning to @gibson042 for triage.

**Comment by erights** [comment]
> where you’d reach for `isHardened` are places that would be better served by calling `harden` regardless of whether it was previously hardened.

Perhaps that's a better solution here as well. If `harden` returns normally, then it was hardened.

**Comment by erights** [comment]
Not yet. On just a moments further thought, this would require passStyleOf to harden instead of rejecting unhardenable things. I anticipate it will eventually be safe to switch over to that, but it is not safe yet.

**Comment by gibson042** [comment]
@kriskowal is there somewhere to put `isTypedArray` where it could be shared by ses and marshal without introducing undesired dependencies? I'm wanting to use it for a change in the latter like
```patch
-          (isFrozen(inner)) ||
-            assert.fail(
-              X`Cannot pass non-frozen objects like ${inner}. Use harden()`,
-            );
+          if (!isFrozen(inner)) {
+            isTypedArray(inner) && assert.fail(
+              X`Cannot pass mutable typed arrays like ${inner}.`,
+            );
+            assert.fail(
+              X`Cannot pass non-frozen objects like ${inner}. Use harden()`,
+            );
+          }
```

**Comment by erights** [comment]
What does `isTypedArray` test?

**Comment by gibson042** [comment]
It's a brand check.

**Comment by erights** [comment]
Jordan-style JS brand check by seeing if a builtin function throws?

**Comment by gibson042** [comment]
Close, but arguably better... this built-in function returns undefined if its receiver lacks the relevant slot: https://tc39.es/ecma262/multipage/indexed-collections.html#sec-get-%typedarray%.prototype-@@tostringtag

**Comment by erights** [comment]
Amazingly weird! But yes, since this does exist, we should use it.

**Comment by kriskowal** [comment]
My preference is for SES to have no dependencies. To that end, I’d prefer to duplicate the brand-check here, but without the no-polymorphism/disallow-dynamic-dispatch ceremony that is necessary before Lockdown but not after. Jordan’s would suffice https://github.com/inspect-js/is-typed-array depending on your weariness of third-party deps that do slightly more than we need.

**Comment by erights** [comment]
Could we just capture and uncurry the `TypedArray.prototype[Symbol.toStringTag]` setter in commons.js ?

**Comment by erights** [comment]
I'm rather agnostic on the specifics. Anything simple, safe, and reliable is fine with me.
