### ISSUE TITLE
Pervasively defend against Object.prototype.value property descriptor tripfall

### ISSUE THREAD

**Issue by kriskowal** [endojs/endo#1329]
Currently, a poorly-vetted shim can damage SES by creating properties on Object.prototype, particularly `value`, which confuses `Object.defineProperties` and `Object.defineProperty`.

We currently don’t allow vetted shims to run between repair and lockdown, but we could defend against this kind of damage by making Object.prototype non-extensible [edited] early, during the repairs phase instead of waiting until lockdown.

We could also erase unknown properties at that phase to defend against pollution from vetted shims that run before repairs.

To defend against this pervasively without repairing and freezing Object.prototype early, we would need to ensure that all property descriptors that pass through our system have a null prototype. We would need adapters for `getOwnPropertyDescriptor` and `getOwnPropertyDescriptors` that change the prototype of descriptors to null, so that idioms like `Object.defineProperties(x, Object.getOwnPropertyDescriptors(y))` work properly in the face of pollution. I’d call that a bridge too far, since this defends against _flaws_ in _vetted_ shims. Lockdown otherwise protects us from guest programs in compartments.

**Comment by kriskowal** [comment]
cc @erights @mhofman

**Comment by erights** [comment]
>  freezing `Object.prototype` early

Only need to make it non-extensible, which is a much more reasonable restriction to impose on vetted shims.

**Comment by kriskowal** [comment]
As discussed out-of-band, we’re protected from Object.prototype tampering after repair because the unknown properties will be erased (or repairs will die trying). Only code running before repair is not protected.

**Comment by kriskowal** [comment]
My feeling is that we should do nothing further to protect against `Object.prototype` pollution that may occur before initialization of SES, repairs, or lockdown. We do not need to actively pull out any existing tests or behaviors that over-protect, but it would be valid to remove them opportunistically.

Please reopen if you believe we should arrive at a different policy.
