### ISSUE TITLE
add readme/mission-statement to SES repo

### ISSUE THREAD

**Issue by katelynsills** [endojs/endo#134]
We need more justification/motivation 

Add code snippets similar to the DWeb Summit talk

**Comment by kriskowal** [comment]
@katelynsills Do you have a link for the DWeb talk?

**Comment by kriskowal** [comment]
@dckc reached out to suggest that the SES README needs to utter “cooperation without vulnerability” and “defensive correctness” as a motivation for using SES.

**Comment by kriskowal** [comment]
Thanks. We now have mission statements in both the SES and Endo directories. The DWeb talk and slides are linked on the Agoric change log, but the API details are very stale now. We’ll have to reprise that talk some time @warner.
