### ISSUE TITLE
Remove or suppress warning: Tolerating undeletable ... === undefined

### ISSUE THREAD

**Issue by Jack-Works** [endojs/endo#1345]
https://github.com/endojs/endo/blob/4da7742e8017d07094ed9b9336a85b6a4d3ee7b6/packages/ses/src/whitelist-intrinsics.js#L292

![image](https://user-images.githubusercontent.com/5390719/198927559-f8a974fc-6e33-4413-9a48-427ae1ab2414.png)

This warning is annoying and does not help too much because we know what we're doing (using core-js)

**Comment by kriskowal** [comment]
We could alternately bundle all the Lockdown warnings under an error group to be less loud and still reveal all these details. @erights?

**Comment by erights** [comment]
Error group is good.
