### ISSUE TITLE
Test ES6 module version of SES directly in browser with `type="module"` on CircleCI

### ISSUE THREAD

**Issue by katelynsills** [endojs/endo#136]
We still need to test using the ES6 module version directly in the browser with `type="module"`. This seems to require spinning up a small server on CircleCI.

**Comment by kriskowal** [comment]
We’ve avoided this issue by annotating `package.json` such that the Endo-bundled version of SES gets used in browsers in lieu of `type="module"`. We should still test `type="module"` in the `ses-integration-test` so I’m leaving this open.

**Comment by kriskowal** [comment]
This is currently exercised in CI since Node.js 16.
