### ISSUE TITLE
compartment-mapper/importHook - npm package expects '.' to resolve to main

### ISSUE THREAD

**Issue by kumavis** [endojs/endo#1363]
compatibility issue with [`superagent@3.8.3`](https://npmfs.com/package/superagent/3.8.3/)

a module specifies `../..` here https://npmfs.com/package/superagent/3.8.3/lib/node/agent.js#L10
which resolves to the package root, and expects that to resolve to the main https://npmfs.com/package/superagent/3.8.3/package.json#L62

**Comment by kriskowal** [comment]
I solved this problem in Guten Tags by creating an alias for `main`. Assuming we normalize `main`, `browser`, and `exports` into a common form, creating aliases for the top-level should be straight-forward

https://github.com/gutentags/system/blob/master/common-system.js#L62

**Comment by kumavis** [comment]
a warning is served when a type=module package does not have its module set but still defaults to index.js and proceeds 
> Default "index" lookups for the main are deprecated for ES modules.
