### ISSUE TITLE
Decouple Far from Marshal

### ISSUE THREAD

**Issue by kriskowal** [endojs/endo#1441]
Currently, Far, passStyleOf, and getInterfaceOf are important underpinning os the Endo object model and, along with E from eventual-send, so copies of these behaviors get captured in every Endo bundle. These concerns are abstract and should not require every Endo bundle to also contain a concrete implementation of marshal. They currently do, but this is an accident of our layering, where `@endo/far` imports the `@endo/marhsal` index just for these utilities.

@erights, @michaelfig and I have constructed a plan to surgically separate `@endo/pass-style` such that `@endo/far` reexports it and `@endo/marshal` depends upon it (and reexports it in the interest of preserving API backward-compatibility for resources that couple them directly).

To that end:

- [x] #1438 scaffold a new `pass-style` package
- [ ] #1439 refactor `pass-style` out of `marshal`
- [ ] #1442
- [ ] #1443

**Comment by erights** [comment]
Interesting. Before seeing this, I already did #1442 as part of #1439. I could easily do #1443 as well. I'm inclined to. Then #1439 would fix #1441 , #1442, and #1443. Is this change of plans ok? Is #1439 consistent with your plans?

@michaelfig , I added you as a reviewer on #1439. Feel free to respond to these questions there.

**Comment by erights** [comment]
Added fix to #1443 to #1439

**Comment by kriskowal** [comment]
Yes, your plans are all good.
