### ISSUE TITLE
Will exportheavy.js test file need fixing?

### ISSUE THREAD

**Issue by erights** [endojs/endo#1445]
Is

https://github.com/endojs/endo/blob/c4b3fffdbf6b3be8c2302d40f774f5415b6802ea/packages/static-module-record/test/fixtures/exportheavy.js#L5-L21

a problem? It looks like it was somehow referencing the old locations for files that are moving to `@endo/pass-style`. But I don't see how it was actually referencing anything. Help?

**Comment by kriskowal** [comment]
This should not require any change. The file is just a test fixture for verifying the static analysis behavior.

**Comment by erights** [comment]
Great! Closing.
