### ISSUE TITLE
Repair types following extraction of @endo/pass-style from @endo/marshal

### ISSUE THREAD

**Issue by erights** [endojs/endo#1446]
https://github.com/endojs/endo/pull/1439 is the PR that extracts passStyleOf and friends from @endo/marshal into the newly created @endo/pass-style . However, after getting everything but linting working, I then had to add https://github.com/endojs/endo/commit/bf9fa86f80b1fdd8c05daff4d67fad355d3de409 only to suppress the resulting type errors and import-order complaints.

I just blindly suppressed them because I could not figure out how to repair them properly. This issue is the reminder that these still need to be repaired.

See https://github.com/endojs/endo/pull/1439#pullrequestreview-1248878819

**Comment by erights** [comment]
@turadg , ok if I give this to you?

**Comment by kriskowal** [comment]
What’s the status of this?

**Comment by turadg** [comment]
Not yet prioritized

**Comment by erights** [comment]
@turadg , would this be fixed by your recent Passable-typing PR?

**Comment by turadg** [comment]
@erights i expect so

**Comment by turadg** [comment]
Looks like this was done at some point
