### ISSUE TITLE
TS `never` confused in endo but not in agoric-sdk

### ISSUE THREAD

**Issue by erights** [endojs/endo#1450]
The `throwLabeled` function defined at https://github.com/Agoric/agoric-sdk/blob/bfbb808fa9f4151844516ef0ca8af1a8b6bf98ae/packages/internal/src/utils.js#L103-L120 has no lint problems.

Currently I'm in progress in migrating the patterns abstractions from `@agoric/store` into a separate `@endo/patterns`. Because that code depends on `throwLabeled` I made a copy there. However, there is causes a lint error:

/Users/markmiller/src/ongithub/endojs/endo/packages/patterns/src/utils.js
  70:1  warning  JSDoc @returns declaration present but return expression not available in function  jsdoc/require-returns-check

This difference shows up in vscode as well. The left pane is my copy in my new `@endo/patterns` package. The right pane is the one in `@agoric/internal`. As you can see, locally there is no difference.
<img width="1530" alt="image" src="https://user-images.githubusercontent.com/273868/213059761-64877084-fd76-4592-8bb4-b4e364b0fe0b.png">

The lint error makes no sense to me. The function can only complete via a `throw` statement. TS is supposed to be happy with `@returns {never}` for that, which makes a lot of sense.

**Comment by erights** [comment]
See https://github.com/endojs/endo/pull/1451

**Comment by turadg** [comment]
That Eslint rule can get confused by TS types. How I've been working around that is a newljne after the JSdoc comment.

**Comment by turadg** [comment]
Not sure. Maybe changes in eslint-plugin-jsdoc. https://github.com/endojs/endo/pull/1453 to bump to latest.

**Comment by kriskowal** [comment]
It’s been a nearly year. Has this problem persisted?

**Comment by erights** [comment]
Don't close it yet. Likely trivial PR coming up shortly.

**Comment by erights** [comment]
At https://github.com/endojs/endo/pull/1930
