### ISSUE TITLE
Types: Documenting TypeScript error 2775 for `assert.makeAssert()(false)` somewhere?

### ISSUE THREAD

**Issue by SMotaal** [endojs/endo#1452]
Since we are shipping type definitions, I was wondering if edge cases like this one which are easy to document could be worthwhile mentioning in the hovering `docs` to help demystify things for the endusers.

This is just one potential case where this question maybe worthwhile asking. It helps to consider how such nuances would break the dx for developers when TypeScript is merely part of their editor, imho.

> **Note**: I opt to use <ins>`<ins>` tags</ins> for my unavoidable edits.

---

**In this specific case**:

Given, the following minimal `assert` function:

```ts
/** @param {any} value @return { asserts value } */
const assert1 = (value) => { if (!value) throw new Error('Expected true'); }
```

For this to work, it needs to have explicit type annotations on the declaration itself.

The expected behaviour is that code following a `falsy` assertion would be unreachable.

So, this works as expected:

```ts
() => { assert1(false); … };
//                      ^?
// @errs: [Error: 7027]: Unreachable code detected.
```

And, this also works because the type annotation is on the declaration:

```ts
/** @type { typeof assert1 } */
const assert2 = assert1;

() => { assert2(false); … };
//                      ^?
// @errs: [Error: 7027]: Unreachable code detected.
```

But, not this one since the type annotation is not on the declaration:

```ts
/** We expect this to work like `assert1` */
const assert3 = assert1;

() => { assert3(false); … };
//      ^?
// @errs: [Error: 2775]: Assertions require every name in the call target to be declared with an explicit type annotation.

() => { assert3(false); … };
//                      ^?
// @errs: ‹no›
```

---

**Questions**:

- Do we want to include any kind of documentation for such nuances?<ins>

<ins>

- Would it make sense to include links in the popovers?

- Where is the best place to annotate this particular gotcha for the developer?
  > Ideally on the `assert` returned by the `makeAssert` function?

</ins>

- …

**Comment by turadg** [comment]
This sounds like more like a [Discussion](https://github.com/endojs/endo/discussions) than an issue. 

> Do we want to include any kind of documentation for such nuances?

I think this is a standard caveat with TypeScript. `any` is broader than truthy so the assertion doesn't add information. When there's no type annotation, the type is implicitly `any`.

We could remind people of this fact of TypeScript. I don't see that as being worthwhile, since it's something one has to learn about TS and not Endo.

We could also enable `noImplicitAny` in the packages. But that's a hassle to use with `.js` syntax because an explicit `any` is more verbose than in `.ts`.

**Comment by erights** [comment]
Is the convention introduced by https://github.com/endojs/endo/pull/1431 relevant?

**Comment by SMotaal** [comment]
> Is the convention introduced by #1431 relevant?

@erights, I'm still looking through in more depth, but my initial take is that this would be extraneous compared to those error-codes.

I wonder if maybe it belongs in a Types-specific documentation somewhere.

> I don't see that as being worthwhile, since it's something one has to learn about TS and not Endo.

@turadg I am aligned with you that this is a TypeScript error.

This being the case, my initial thought was a brief mention in the respective comment for the TypeScript definition files only.

For instance here, `makeAssert` would mention TypeScript error 2775 with a link maybe.

The error code matching the hover for the error itself would help prevent needless searching.

This is especially a concern for more JavaScript-than-TypeScript-oriented developers, imho, since editors like VSCode are reporting an error resulting from our use of more advanced types that rub against a rather peculiar (albeit rational) restriction.

**Comment by turadg** [comment]
@SMotaal if you'd like to push a PR adding docs to the `MakeAssert` type to inform users of the potential gotcha described here, I would review it.

**Comment by SMotaal** [comment]
@turadg I appreciate the assertiveness NPI 😊 but first to clarify what a PR can do in this case, types wise…

We have this description here:

https://github.com/endojs/endo/blob/69b61e3f9a0af9a9714413708ddb9bcf68772846/packages/ses/src/error/types.js#L221-L241

That description is not what is showing for the consumers per #1392.

Hence my trying to appreciate the internal priorities of the team to make sense of what would be constructive discussion and contribution.

Clarity on what will change to address #1392, imho, is needed first. Adding it there now is may not address depending on what ends up changing.

**Comment by SMotaal** [comment]
@erights I'm curious if it could make sense to document gotcha's in a little explainer in a similar fashion that we can link to.

I wonder if this could be a subdirectory or a different directory altogether placed elsewhere in the monorepo.

FWIW, the inclination I am having for a longer-term path forward would likely involve harmonize the extraneous aspects related to types within the monorepo and introduce a root folder where they can be kept in one place. In this scenario, documentation on such gotchas can live directly there. This is all still raw as I am working to figure out the complexities involved and how they affect all parties involved.
