### ISSUE TITLE
ses-ava should not mix exports and side-effects

### ISSUE THREAD

**Issue by gibson042** [endojs/endo#1467]
(split from #1235)

https://github.com/Agoric/agoric-sdk/pull/5774/

**Motivation**

Hacks around side-effects of prepare-test-env-ava such as https://github.com/endojs/endo/pull/1439#discussion_r1070430689

**Acceptance criteria**
- module imports either have side-effects OR bindings

**Comment by turadg** [comment]
closing per https://github.com/endojs/endo/pull/2133#issuecomment-1992647735
