### ISSUE TITLE
Debugging in Safari is not working for script executing inside SES

### ISSUE THREAD

**Issue by argp1** [endojs/endo#1490]
Steps to reproduce:
1. Run the demo mentioned [here](https://github.com/endojs/endo/blob/686ab61802c0e5206b14f4b91d499e3873555cd4/packages/ses/demos/console/index.html#L18),
2. Put the `debugger` statement anywhere in script code.
3. Open the Safari developer tools.
4. Click on `Execute` button

**Result**: The script doesn't break on debugger statement in Safari. However in Chrome and Firefox, debugging works fine.
**Workaround**: If we add following function [here](https://github.com/endojs/endo/blob/686ab61802c0e5206b14f4b91d499e3873555cd4/packages/ses/src/strict-scope-terminator.js#L59), the issue gets fixed and we can debug in Safari.

```
  // Note: This is a bug of Safari.
  // In Safari, scope handlers call the ownKeys trap, which is not defined. 
  // This causes the alwaysThrowHandler proxy handler to be called and an error will be thrown.
  // In order to create a scope handler, buildScopeHandler must handle ownKeys
  ownKeys(target) {
    return Reflect.ownKeys(target);
  },
```

Please let me know if you need any additional information.

**Comment by argp1** [comment]
Hi @erights , wanted to check if there is any update on this. Please let me know if I can be of any assistance here. Thanks!

**Comment by erights** [comment]
Hi @argp1 , 
thanks for reporting! And sorry for the terribly late response.
I verified that Safari still has this problem. Has the bug been reported to Safari yet?

Hi @mhofman , 
I'm happy to do a PR adding the `ownKeys` method to some proxy handler, as @argp1 suggests. But which proxy handler do you think is best for this?

**Comment by argp1** [comment]
@erights , Nope, I haven't reported this to Safari. Even if Safari fixes this, the older versions of Safari will still have this problem. So I think we should handle it in SES itself.

**Comment by mhofman** [comment]
@erights we likely want to add an `ownKeys` trap to the `scopeProxyHandlerProperties` as @argp1 suggests, but instead of calling `Reflect`, it likely should just `return [];`

**Comment by erights** [comment]
Both the `scopeProxyHandlerProperties` in strict-scope-terminator.js and the `scopeProxyHandlerProperties` in sloppy-globals-scope-terminator.js ?

**Comment by erights** [comment]
Nevermind. I see that one includes the other. Proceeding...

**Comment by erights** [comment]
See https://github.com/endojs/endo/pull/1651
