### ISSUE TITLE
eslint-plugin-jsdoc v40 is issuing lint warnings

### ISSUE THREAD

**Issue by gibson042** [endojs/endo#1495]
#1453 [bumped the resolved version of eslint-plugin-jsdoc from 30.7.13 to 40.0.0](https://github.com/endojs/endo/pull/1453/files#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2de), which pulled in [changes to default `plugin:jsdoc/recommended` configuration](https://github.com/gajus/eslint-plugin-jsdoc/compare/v30.7.13..v40.0.0) that are generating [lint warnings](https://github.com/endojs/endo/actions/runs/4156705602/jobs/7190680401#step:9:41) disruptive to potential use of `yarn lint-fix`. For example:
> ```
> /home/runner/work/endo/endo/packages/patterns/src/types.js
> Warning:    62:1  warning  Should be no multiple asterisks on middle lines          jsdoc/no-multi-asterisks
> Warning:   133:1  warning  Expected no lines between tags                           jsdoc/tag-lines
> Warning:   214:1  warning  Expected no lines between tags                           jsdoc/tag-lines
> Warning:   432:1  warning  Expected no lines between tags                           jsdoc/tag-lines
> Warning:   459:1  warning  Should have no text on the "0th" line (after the `/**`)  jsdoc/multiline-blocks
> Warning:   497:1  warning  Expected no lines between tags                           jsdoc/tag-lines
> ```

We should resolve the warnings, either by overriding the new default configuration or by updating files to accommodate it.

**Comment by erights** [comment]
> We should resolve the warnings, either by overriding the new default configuration or by updating files to accommodate it.

We should override this new default. There is nothing about obeying this rule that improves the readability of the text in question. It only subtracts value.
