### ISSUE TITLE
Node 14 sunset

### ISSUE THREAD

**Issue by naugtur** [endojs/endo#1540]
https://nodejs.dev/en/about/releases/

Node 14 maintenance ends this month. We might want to switch everything to newer versions.

**Comment by erights** [comment]
This would let us assume `Object.hasOwn` and phase out `hasOwnPrototypeOf`. What else?

**Comment by naugtur** [comment]
String.replaceAll
Promise.any
WeakRef
Logical Assignment

Got them all from:
https://node.green/#ES2021
https://node.green/#ES2022
