### ISSUE TITLE
Realms Issue #200: internal shim error in Safari: unexpected scope handler trap called: getPrototypeOf

### ISSUE THREAD

**Issue by katelynsills** [endojs/endo#155]
[proposal-realms issue #200](https://github.com/tc39/proposal-realms/issues/200)

**Comment by kriskowal** [comment]
We need to attempt to reproduce this on SES-shim today, and add a test if one does not already exist.

**Comment by erights** [comment]
Good news! Today I pinged at https://bugs.webkit.org/show_bug.cgi?id=195534 . They tested, report it is fixed, and closed their bug. I'm leaving this open only until we do our own test.
