### ISSUE TITLE
Shared Symbol intrinsic

### ISSUE THREAD

**Issue by kriskowal** [endojs/endo#1577]
Currently, Compartments share `globalThis.Symbol` with the start compartment, the realm global environment. Consequently, if the host has any symbols that are not recognized by SES’s permits, Lockdown will fail.

We should instead create a separate `Symbol` shared intrinsic, like the repaired `Function` or `Date`, that shares the global prototype of `Symbol`, disables the shared prototype constructor, and only includes the symbols that SES will permit in shared compartments.

**Comment by erights** [comment]
Clarification: The reason why lockdown will fail is because these well-known-symbol properties are non-configurable. Otherwise our whitelist mechanism would safety remove them.
