### ISSUE TITLE
Bundle tools should handle EMFILE gracefully

### ISSUE THREAD

**Issue by kriskowal** [endojs/endo#1593]
Bundling opens a lot of concurrent file descriptors, sometimes more than are available, especially when running the bundler concurrently. We should address this in general, but specifically for the `bundle-source` tool.

Tools like `bundle-source` currently construct their file system capabilities from `'fs'` module, which does not gracefully handle EMFILE or EAGAIN. The `graceful-fs` package in `npm` takes care of these concerns but does not provide a promise abstraction. We would need to lower the `compartment-mapper` `node-powers` module a layer of abstraction and embrace `fs` callbacks directly to use `graceful-fs` as a drop-in replacement for `fs`.

Alternately, we should implement graceful handling of these errors ourselves in the compartment mapper. This would implicitly improve other existing applications, since the concern of attenuating an `fs` power is currently deferred to the individual application entrypoints.

The author of this issue notes that we could have the best of all worlds had `graceful-fs` been implemented as a powerless adapter and did not import `fs` directly.

**Comment by mhofman** [comment]
Famous last words but I wouldn't expect handling these errors directly from native `fs/promises` API to be a too difficult.

**Comment by warner** [comment]
Note to self: [the particular feature of `graceful-fs`](https://www.npmjs.com/package/graceful-fs) that would help here is:

> Queues up open and readdir calls, and retries them once something closes if there is an EMFILE error from too many file descriptors

That would enable complete usage of the finite number of FDs. The basic "limit parallelism" scheme that I first had in mind would require us to guess how many we could use, and our guess would likely either exceed the environment's limit, or leave some number of FDs unused (nominally leaving some parallelism opportunities, and perhaps thus performance, on the table).

That said, using EMFILE-retried `open()` calls for all files means that opening the final output file might block until some other input file had closed, and perhaps we can't close that input file until we've copied its contents into the output file. To avoid a livelock, we might want to open the (single?) output file *first*, before there's much chance of contention.

**Comment by kriskowal** [comment]
Fixed by #1697.
