### ISSUE TITLE
M.nat() allows safe number?

### ISSUE THREAD

**Issue by dckc** [endojs/endo#1597]
The docs say yes:

https://github.com/endojs/endo/blob/0ab46f79216e9802136e8bc4365e402dad1d796b/packages/patterns/src/types.js#L305-L308

but the implementation says no:

https://github.com/endojs/endo/blob/0ab46f79216e9802136e8bc4365e402dad1d796b/packages/patterns/src/patterns/patternMatchers.js#L837

the tests don't seem to take a side.

**Comment by gibson042** [comment]
I'm responsible for the JSDoc explanation via https://github.com/Agoric/agoric-sdk/pull/6654 , intending to align with [@endo/nat](https://github.com/endojs/endo/blob/master/packages/nat) and in particular observing a distinction between `M.bigint()` and `M.nat()`. But even at the time, that text inaccurately described behavior (which had already updated from `makeMatcher('match:gte', 0n)` to `checkKind(specimen, 'bigint', check) && check(specimen >= 0n, …)` in https://github.com/Agoric/agoric-sdk/pull/6057/files , the former implicitly and the latter explicitly failing on non-bigint input).

Regardless, I suspect that the intent is actually to align with the text and accept both bigint and number values that are in-range. @erights, can you weigh in?

**Comment by erights** [comment]
The documentation is stale. The code is correct. `M.nat()` should only accept non-negative bigints.

This is all fossilized remains from Agoric starting before we could, ahem, count on bigints. See https://github.com/Agoric/nat#validators-and-coercers on Validators and Coercers. Patterns can only be validators, so we must insist on bigints to match `Nat`'s output, which is to say, `Nat`'s role as a coercer.

**Comment by erights** [comment]
And we should insist on bigints anyway. The natural numbers that Peano recognized don't lose precision when they get large ;).
