### ISSUE TITLE
Publish an article explaining the property override hazard and its implications

### ISSUE THREAD

**Issue by kriskowal** [endojs/endo#1598]
ECMAScript 5 introduced properties to JavaScript, the advancement to the “Meta Object Protocol” (MOP) that laid the foundation for getters and setters, proxies, and tamper-proof objects. This was a huge step forward for hardening JavaScript such that multiple parties could safely share a JavaScript realm, particularly because of `Object.freeze`, which makes an object irreversibly tamper-proof. The MOP also made Proxies conceivable. The protocol came with a couple downsides. For one, introducing getters and setters introduced an reentrance or interleaving hazard: programs cannot assume accessing a property will have no side-effects or synchronously reenter code that shares its lexical scope. The other, is the Property Override Hazard, which some (but not all!) of the authors of ECMAScript 5 apologize for, calling it the Property Override *Mistake*.

The hazard of property override is that a program that works when certain intrinsic objects like `Object.prototype` are _not_ frozen will cease to function properly after freezing those objects.

The following program works:

```js
'use strict';
function MyClass() {}
MyClass.prototype.toString = function toString() {};
```

However, if we freeze the `Object.prototype`, or even merely make the `Object.prototype.toString` property non-configurable, this program does not work:

```js
'use strict';
Object.freeze(Object.prototype);
function MyClass() {}
MyClass.prototype.toString = function toString() {};
```

To mitigate the problem, you can use `defineProperty` to “configure” the property instead of merely assigning.

```js
'use strict';
Object.freeze(Object.prototype);
function MyClass() {}
Object.defineProperty(MyClass.prototype, 'toString', {
  value: function toString() {},
  writable: true,
  enumerable: false,
  configurable: true,
});
```

Folks who claim this was a mistake suggest the original example should work, and that overriding a property by assignment should work, even if the property by the same name up the prototype chain is marked non-configurable, on the grounds that the assignment is to the instance, not the instance’s prototype. The defenders of the property override hazard (presumably) contend that forcing the use of defineProperty reduces the possibility of a subclass accidentally overriding a property (citation needed).

The problem does not affect `class` notation, even in cases where the author appears to be assigning in the class block, because all such instructions are interpreted as property definition, not truly assignment. The following example works fine, despite the property override hazard, because `property = 20` has the effect of `Object.defineProperty(this, 'property', { value: 20, writable: true, enumerable: true, configurable: true })` when we construct an instance of `SubClass`.

```js
class BaseClass {
  property = 10;
}
Object.freeze(BaseClass.prototype);

class SubClass extends BaseClass {
  property = 20;
}
```

Consequently, we expect this problem to fade with time.

In an article about this topic, I understand we can reach for an explanation in the differences between prototypes as used in Self and how they’ve come to be used in JavaScript in practice.

cc @erights

**Comment by kriskowal** [comment]
We can also note that in practice, this problem usually only occurs because of a couple common forms. The first is `toString` assignment as above, but also `constructor` assignment in a common pattern for class definition that predates `class` syntax. The problem exists for any property name on `Object.prototype` after frozen. The hazard can occur for any prototype chain that overrides, but such problems are rare in practice.

**Comment by kriskowal** [comment]
To be decided: a venue for this article.

**Comment by kriskowal** [comment]
For future reference, @erights dug up Allen’s words:

> Not a Mistake — Allen Wirfs-Brock 2012/01/09 20:45
> 
> This was not a mistake in ES5/5.1 and it is not a bug. It is a semantics that goes all the way back to ES1. It is also a behavior which makes complete sense from a prototypal inheritance perspective and can be found in the Self language.
> 
> The basic idea is that the properties prototype object are shared parts of all of inheriting child object. Modifying such a shared part by a child, introduces a local change that is visible to that child (and its children) so this requires creation of a “own” property on the child. However, read-only properties can not modified (by normal means, eg assignment) so there is no need to create a “own” copy. Assigning to an inherited read-only property or a “own” read-only property should have the same affect (whether it is ignoring the assignment, throwing, etc.). Allowing assignment to an inherited read-only property would break the invariant that that a prototype’s readonly property is an immutable value that is shared among all children of the prototype.
> 
> If there was a mistake in designing ES5, it was allowing Object.defineOwnProperty to create child properties that over-ride inherited read-only data properties. This broke an invariant that previously existed in the language but this invariant was already violated by some pre-ES5 clause 15 objects, (eg the writability of the prototype property of some children of Function.prototype). However, I think the ES5 decision was probably the right one given the legacy clause 15 usages and the overall reflective nature of defineOwnProperty).
> 
> Finally, this issue was given plenty of attention in during the development of ES5. In various drafts, the ES5 specification actually broke the legacy behavior causing it to behave similarly to what is suggested by this strawman. Those specification bugs were corrected in order to ensure that the semantics specified by ES3 and earlier editions were not changed by ES5.

https://web.archive.org/web/20141230041441/http://wiki.ecmascript.org/doku.php?id=strawman:fixing_override_mistake

And a useful article on property definition vs assignment

https://exploringjs.com/deep-js/ch_property-assignment-vs-definition.html

**Comment by kriskowal** [comment]
Also, more from Allen https://esdiscuss.org/topic/set-and-inherited-readonly-data-properties#content-2

**Comment by kriskowal** [comment]
Subscribing @jessysaurusrex for more eyes for review.

**Comment by mhofman** [comment]
> The following example works fine, despite the property override hazard

While this example highlights that class fields also have define semantics besides looking like assignments (which have set semantics), it would not trigger the override mistake even if class fields had set semantics. That's because class fields create instance properties, and does not impact the prototype unlike class methods.

A confusing way to show how the override mistake is actually not a problem for class fields would be to explicitly define a property on the super prototype. Another way would be to shadow a super method with a class field, like with a bound function:

```js
class BaseClass {
  handleEvent(e) {};
}
Object.freeze(BaseClass.prototype);

class SubClass extends BaseClass {
  handleEvent = this.handleEvent.bind(this);
}
```

**Comment by kriskowal** [comment]
Published as an Agoric SDK discussion, could go elsewhere as well https://github.com/Agoric/agoric-sdk/discussions/8513

**Comment by erights** [comment]
Why cross-post a duplicate of article already in endo repo, rather than just point at that one as canonical? Such duplication creates maintenance and pointless divergence hazards.
