### ISSUE TITLE
Use conventional commits with lerna version

### ISSUE THREAD

**Issue by michaelfig** [endojs/endo#16]
If we adhere to [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) then we get semantic versioning and CHANGELOG.md generation basically for free.

[Discussion of `lerna version` options](https://www.npmjs.com/package/@lerna/version#prerelease) suggests different `--conventional-commits` flags that can be used to automatically bump the semantic versions, use prerelease or graduated variants.

Let's discuss this here!

**Comment by michaelfig** [comment]
@jfparadis @warner I'd like you to have a look at this in your spare time.  Not urgent, but may make principled releases a lot easier.

**Comment by jfparadis** [comment]
@michaelfig @warner @erights @dtribble 

One thing we have to decide is whether we go monoversion or polyversion for the git repo. This absolutely needs to be supported by tooling. But there are two paths:

Monoversion:
- all package versions are the same, all updated at the same time
- this is what Babel uses:
https://github.com/babel/babel/tree/master/packages
- good for tightly integrated systems (like here, we publish one rollup)
- simpler to manage, guarantees that everything at the same version runs
- simpler to automate

Polyversion
- this is what React uses
https://github.com/facebook/react/tree/master/packages
- good for granular publication
- users of SES don't need to manage SES (which will probably stay at 1.0.0 or close), what will change is the version of the dependencies.

*Important*: with polyversion (current situation), we could change one package (say `compartment-shim`) and no code changes in the `ses` package itself, and there is no update to its version. Therefore a security fix in `compartment-shim` might not trigger a new version of SES. In other words, users of SES will need to do their audit and update their lock files, not their `package.json`. We need to fully understand and be comfortable with that.

**Comment by michaelfig** [comment]
> Important: with polyversion (current situation), we could change one package (say compartment-shim) and no code changes in the ses package itself, and there is no update to its version. Therefore a security fix in compartment-shim might not trigger a new version of SES. In other words, users of SES will need to do their audit and update their lock files, not their package.json. We need to fully understand and be comfortable with that.

With polyversion, we can also manually bump the dependent packages.  That's no worse than what we're currently doing.  Or, we could make a PR against lerna that would do this automatically.

**Comment by jfparadis** [comment]
> With polyversion, we can also manually bump the dependent packages. 

Yes, that's how polyversion works. Each dependent package evolved independently.

**Comment by kriskowal** [comment]
Status: We are starting to use conventional commits but have not yet started using Lerna to publish versions. We are still using the polyversion approach, and have no particular reason to revisit this approach. I’ve been publishing manually, through the process outlined in `CONTRIBUTING.md`. We have fewer packages now than at the time of this issue’s creation, with intent to make few more, and intent to remove some, and manually publishing has not been too cumbersome. I’m comfortable with the manual review of `NEWS.md` between releases, which I don’t believe `lerna` adequately addresses with conventional commits and updates to `CHANGELOG.md`.

**Comment by kriskowal** [comment]
Will reassess at next week’s Agoric SES meeting. @michaelfig

**Comment by michaelfig** [comment]
Here's a pointer to agoric-sdk's [MAINTAINERS.md](https://github.com/Agoric/agoric-sdk/tree/master/MAINTAINERS.md).

**Comment by kriskowal** [comment]
This has begun with https://github.com/endojs/endo/pull/762
