### ISSUE TITLE
`AsyncLocalStorage` from `node:async_hooks` is broken

### ISSUE THREAD

**Issue by michaelfig** [endojs/endo#1657]
@mhofman, yet another instance of random async hooks symbols causing problems under SES.

I'm working with a library that is advertised to use `AsyncLocalStorage` under the covers, and it throws:

```
Error#1: Object [Promise] {
  [Symbol(kResourceStore)]: BaseContext {
    _currentContext: Map(0) {},
    getValue: {},
    setValue: {},
    deleteValue: {}
  }
} - Must not have any own properties: [ Symbol(kResourceStore) ]

  at Array.every (<anonymous>)
  at deeplyFulfilledObject (packages/internal/src/utils.js:186:10)
```

I hope we can also patch this in `node-async_hooks-patch.js`.  I have a workaround for now.

**Comment by mhofman** [comment]
It might not be possible to patch that one, or at least not in the same way. Each `AsyncLocalStorage` instance seem to [create its own unique symbol](https://github.com/nodejs/node/blob/8658efe376838821be7f9b4ff25c8bc2e229bb92/lib/async_hooks.js#L278C14-L278C14), which it then attaches to various resources ("cheap" WeakMap trick).

An alternative may be to monkey patch `AsyncLocalStorage` to make it use a WeakMap instead.
