### ISSUE TITLE
does removeProperties visit prototypes?

### ISSUE THREAD

**Issue by warner** [endojs/endo#168]
[edit 2020-09-15 @kriskowal]

@erights volunteers to verify that we have addressed this.

---

@dtribble and I were looking at `removeProperties.js`, and we noticed that the `clean()` function does a recursive traversal of named properties (`Object.getOwnPropertyNames`) but is *not* traversing the `Object.getPrototypeOf` links. It uses `getPrototypeOf` to implement the `*` permission value, but that only appears in `getPermit()` and not in the traversal code.

As a result, we won't be applying the whitelist to any of the prototypes, unless they're reachable by other named pathways like `Number.prototype`. Is this enough? Are there any primordials that are only reachable by following an `Object.getPrototypeOf()` from some named object?

**Comment by Tartuffo** [comment]
@erights Is this still an issue?

**Comment by erights** [comment]
Leave open until we've verified. The test suggested above is easy and sufficient.

**Comment by Tartuffo** [comment]
@erights does this need to be tested and fixed/closed as part of Mainnnet 1?

**Comment by erights** [comment]
not mn-1

**Comment by Tartuffo** [comment]
@erights This does not have an area label that is covered by our weekly tech / planning meetings. Can you assign the proper label? We cover: agd, agoric-cosmos, amm, core economy, cosmic-swingset, endo, getrun, governance, installation-bundling, metering, run-protocol, staking, swingset, swingset-runner, token economy, ui, wallet, zoe, zoe contract

**Comment by Tartuffo** [comment]
@erights needs to check, this is probably just a small amount of work, if it is not already doing what it should.

**Comment by kriskowal** [comment]
```temp
import 'ses';
const bogus = { __proto__: Object.prototype };
Array.prototype.__proto__ = bogus;
lockdown();
```

```
ses ❯ node temp.js
(TypeError#1)
TypeError#1: Unexpected intrinsic intrinsics.%ArrayPrototype%.__proto__ at undefined

  at visitPrototype (packages/ses/src/permits-intrinsics.js:149:11)
  at visitProperties (packages/ses/src/permits-intrinsics.js:261:5)
  at isAllowedPropertyValue (packages/ses/src/permits-intrinsics.js:159:7)
  at isAllowedProperty (packages/ses/src/permits-intrinsics.js:222:14)
  at visitProperties (packages/ses/src/permits-intrinsics.js:272:26)
  at whitelistIntrinsics (packages/ses/src/permits-intrinsics.js:315:3)
  at repairIntrinsics (packages/ses/src/lockdown.js:325:3)
  at globalThis.lockdown (packages/ses/src/lockdown-shim.js:14:28)
  at packages/ses/temp.js:4:1
```

I believe this confirms the desired behavior. Please reöpen otherwise.
