### ISSUE TITLE
Links are broken in npm package pages

### ISSUE THREAD

**Issue by gibson042** [endojs/endo#1754]
## Describe the bug

For example, the types.js link at the bottom of https://www.npmjs.com/package/@endo/patterns _should_ point at https://github.com/endojs/endo/blob/master/packages/patterns/src/types.js like the one in its source at https://github.com/endojs/endo/blob/master/packages/patterns/README.md , but instead points at the nonexistent https://github.com/endojs/endo/blob/HEAD/src/types.js .

We can probably address this in the publication process.

**Comment by kriskowal** [comment]
We need to add a `directory` entry to the `repository` in `package.json`. That should fix the npm rendering of relative links.
