### ISSUE TITLE
@endo/zip conflicts with browser Blob usage

### ISSUE THREAD

**Issue by dckc** [endojs/endo#1811]
## Describe the bug

I recently prototyped a browser-based bundle explorer tool:

  - https://github.com/Agoric/agoric-sdk/discussions/8416

I tried to use `@endo/zip` but the endo `ZipReader()` constructor depends on the `BufferReader` implementation:

```js
  constructor(data, options = {}) {
    const { name = '<unknown>' } = options;
    const reader = new BufferReader(data);
```

I don't see a way to slot in a `BlobReader`.

I suppose I could have used a `Buffer` shim for the browser, but I had the data in a `Blob`. It turned out to be easier to use [zip-loader](https://www.npmjs.com/package/zip-loader).

cc @kriskowal

**Comment by mhofman** [comment]
`BufferReader` takes an `ArrayBuffer` which [can be obtained from a `Blob`](https://developer.mozilla.org/en-US/docs/Web/API/Blob/arrayBuffer). I'm not sure where `Buffer` comes in.

**Comment by mhofman** [comment]
Btw, the type looks wrong on `ZipReader`, it likely takes an `ArrayBuffer`, not an `UInt8Array`...

**Comment by kriskowal** [comment]
Interoperating with other zip implementations is a win I’ll take. But, `@endo/zip` uses `Uint8Array` as the coin of its realm.

These steps should be sufficient to bridge:

```js
const buffer = await blob.arrayBuffer();
const bytes = new Uint8Array(buffer);
const zip = new ZipReader(bytes);
```

**Comment by mhofman** [comment]
step 2 seem to only be necessary to satisfy types.

**Comment by dckc** [comment]
> ... I'm not sure where node `Buffer` comes in.

oops! Looks like I was just reading too fast.
