### ISSUE TITLE
Establish Hardened JavaScript (ses) support for vetted shims by September, 2023

### ISSUE THREAD

**Issue by aj-agoric** [endojs/endo#1818]
## What is the Problem Being Solved?
In support of the MetaMask Grant Process,  we aim to support establishing hardened JavaScript (ses)

## Description of the Design
Hardened JavaScript: a shim for hardened JavaScript, suitable for making a realm suitable for object capability programming and multi-tenant realms.
“Vetted shims”: Allow other shims to run after SES modifies the language and when it hardens the language, so they can extend the shared intrinsics.
Improve diagnostics for debugging, to potentially include improvements to the transparency of error stacks.

**Comment by kriskowal** [comment]
Completed #422
