### ISSUE TITLE
Compartment Mapper: Support for generating unconfined multi-package bootstrap scripts. June 2023

### ISSUE THREAD

**Issue by aj-agoric** [endojs/endo#1821]
## What is the Problem Being Solved?
Compartment Mapper:
Support for generating unconfined multi-package bootstrap scripts. June 2023
From [MetaMask Requirements Doc](https://docs.google.com/document/d/16u_JpaMNc-5Xp4l0fQn3OPAWFUIX-5gxtPWuIu6-fQ0/edit)

## Description of the Design
coming

**Comment by kriskowal** [comment]
Completed https://github.com/endojs/endo/pull/1650
