### ISSUE TITLE
Pet Daemon: Prototype of confined, bundled worker caplets or “worklets”, February 2023

### ISSUE THREAD

**Issue by aj-agoric** [endojs/endo#1824]
## What is the Problem Being Solved?
Pet Daemon: Prototype of confined, bundled worker caplets or “worklets”, February 2023
From Metamask [Requirements Doc](https://docs.google.com/document/d/16u_JpaMNc-5Xp4l0fQn3OPAWFUIX-5gxtPWuIu6-fQ0/edit)

**Comment by kriskowal** [comment]
Completed in the `endo` branch.
