### ISSUE TITLE
Pet Daemon: Prototype of local mail delivery, August 2023

### ISSUE THREAD

**Issue by aj-agoric** [endojs/endo#1827]
## What is the Problem Being Solved?
Prototype of local mail delivery, August 2023
From [MetaMask Requirements](https://docs.google.com/document/d/16u_JpaMNc-5Xp4l0fQn3OPAWFUIX-5gxtPWuIu6-fQ0/edit)

**Comment by kriskowal** [comment]
Completed in the `endo` branch.
