### ISSUE TITLE
`Promise.withResolvers` is unexpectedly removed

### ISSUE THREAD

**Issue by doodlewind** [endojs/endo#1849]
## Describe the bug

We are using SES for simulating sandbox, and recently we found that the newly added native API `Promise.withResolvers` ([proposal](https://github.com/tc39/proposal-promise-with-resolvers)) is not recognized and removed by SES.

## Steps to reproduce

Call `lockdown()` in latest Chrome environment.

## Screenshots

<img width="901" alt="image" src="https://github.com/endojs/endo/assets/7312949/40da2c6c-8e59-4312-90d1-d15340738dc0">

**Comment by kriskowal** [comment]
Thanks, @doodlewind. Always appreciate planned work like this. Please do find us in [Matrix](https://matrix.to/#/!MYcRZqNhDImDvJSOCX:matrix.org?via=matrix.org&via=luxaritas.com&via=alteck.club) and tell us more about your application. We always appreciate such stories and having folks to engage about emerging changes.
