### ISSUE TITLE
ses: Permit Symbol.dispose, Symbol.asyncDispose

### ISSUE THREAD

**Issue by kriskowal** [endojs/endo#1927]
## What is the Problem Being Solved?

[Explicit Resource Management](https://tc39.es/proposal-explicit-resource-management/) is Stage 3 and we should permit Symbol.dispose and Symbol.asyncDispose under Hardened JavaScript

**Comment by mhofman** [comment]
I thought they were already added in https://github.com/endojs/endo/pull/1578

**Comment by kriskowal** [comment]
I see now that they were and why my grep didn’t reveal them. Thanks.

**Comment by dckc** [comment]
what package versions should this appear in?

looks like ses 0.18.5
https://github.com/endojs/endo/blob/master/packages/ses/NEWS.md#v0185-2023-07-14

yes, that explains why someone reported seeing

```
Removing intrinsics.Symbol.dispose
Removing intrinsics.Symbol.asyncDispose
```

after doing `yarn create @agoric/dapp --dapp-template dapp-offer-up demo`: that depends on ses@0.18.4
