### ISSUE TITLE
Windows broke atomic rename

### ISSUE THREAD

**Issue by kriskowal** [endojs/endo#1955]
## Describe the bug

Per https://github.com/nodejs/node/issues/29481, Windows does not support atomic swap (POSIX rename semantics) by default when the target file exists. Since CI caches the target for some tests, we’re seeing CI errors on Windows only like https://github.com/endojs/endo/actions/runs/7471064596. To address this, we may need an environment variable or to back off atomic swap on Windows only.

**Comment by mhofman** [comment]
"broke" is a strong word. Looks like Windows never had atomic renames.

**Comment by kriskowal** [comment]
Yeah, true: it did not support POSIX rename. This is manifesting now with the CI cache. I got a test to pass by killing the windows cache. https://github.com/endojs/endo/actions/caches

**Comment by kriskowal** [comment]
> "broke" is a strong word. Looks like Windows never had atomic renames.

WHAT YEAR IS THIS

**Comment by kriskowal** [comment]
Related Node.js issue with some information on the problem https://github.com/nodejs/node/issues/29481
