### ISSUE TITLE
`@endo/cli`: Consider renaming `restart` and/or `reset` commands

### ISSUE THREAD

**Issue by rekmarks** [endojs/endo#1987]
The situation:
- `endo restart` reboots the daemon, destroying all ephemeral state (i.e. memory).
- `endo reset` performs a "factory reset" of the daemon, destroying all ephemeral _and_ persistent state.

I find "restart" and "reset" to be both phonetically and semantically similar words, and suggest that we rename one or both. In particular, `reset` is a pretty innocuous name for the most destructive command of the CLI.

Note that there is also a command `clean` which destroys all ephemeral state without restarting the daemon.

Here are some alternatives:
`restart`:
- `reboot`
- ~`reload`~ (IMO, inappropriate because does not imply turning it off and on again)

`reset`:
- `wipe`
- `purge`
- ~`clear`~ (too similar to `clean`)

**Comment by kriskowal** [comment]
I agree that `reset` is too similar to `restart`.

I would like to keep `restart` since it’s in the `stop` and `start` family.

I am hoping that `clean` has outlived its usefulness and that it can just be deleted.

I would like to reserve `clear` for caches.

I like the absoluteness of `wipe` and `purge`.

I could also buy `factory-reset` by analogy, forgetting all the current user’s state so it can be passed to a new person.

I could also buy `endo clear [--state] [--cache]` etc.

**Comment by rekmarks** [comment]
After ruminating on this some more, I'm partial to `purge`. After all, this is spiritually the "nuke it from orbit" command.

> I would like to keep `restart` since it’s in the `stop` and `start` family.
I find this to be a strong argument for keeping `restart`.

**Comment by dckc** [comment]
I kinda like `purge`, but IME `--purge` is an option to modify something like `uninstall`.
That makes me lean toward `endo clear [--state] [--cache]`.

Hm... it seems that `apt-get purge packagename` now means the same as `apt-get remove --purge packagename`.

Either of these is **vastly** better than the hazard of `reset`.

Even `purge` should probably have an "are you sure?" thing and a `--force` option to skip the confirmation a la [docker system prune](https://docs.docker.com/engine/reference/commandline/system_prune/).

I mean: the premise of this thing is that users record all sorts of policy / authorization info in here. To have it all go "poof!" with one command would be like having a password manager that looses all your passwords if you accidentally click a button... a button which is on the screen during normal usage.

In fact, I'm going to want to back up and version control the policy / authorization info that I put in this thing. I wonder about `dump` and `restore`. Or can I back up the state with git? Is the format part of the API?

**Comment by tgrecojs** [comment]
I believe we're all in agreement that `reset` and `restart` are detrimental to the `endo` developer experience. 

If I recall correctly, @kumavis has also experienced the delightful confusion that stems from executing `reset` when the intention was a simple `restart`. As much as I'll miss these encounters, I can see that our convenience should come first. 🙂

More seriously...

I agree that keeping `restart` intact makes the entire process more manageable, and I would advocate against its removal.

> I hope that `clean` has outlived its usefulness and can be completely removed.
> I think `clear` should be reserved for caches.
> I am open to the idea of implementing `endo clear [--state] [--cache]` etc.

Reflecting on these thoughts from @kriskowal, it seems that implementing `endo clear [--state] [--cache]` could be the most effective approach. What if launching `endo clear` with no flags resulted in the destruction of all ephemeral and persistent state? Would this additional functionality be practical?

**Comment by dckc** [comment]
>  What if launching `endo clear` with no flags resulted in the destruction of all ephemeral and persistent state?

Let's not make destroying persistent state a default. If there's an `endo clear --state`, then `endo clear` should default to *not* doing that.

**Comment by kumavis** [comment]
yeah i got bit by this

agree that we should NOT have both `clean` and `clear`

in favor of **purge** or **factory-reset**. should sound a little scary

**Comment by tgrecojs** [comment]
Agreed. Lapse of judgement there on my behalf....

On that note, I'm inclined to vote for the `endo factory-reset` as I believe it helps protect users from deleting anything they did not intend to delete. I also think something like `--force` flag could be beneficial. Taking it a step further, I think the best experience come from`endo factory-reset` prompting users to answer `Y/N` before executing. 

Interested in hearing thoughts on this two-step process...

Note: **I'm equally fine with `factory-reset` and `purge`** (@kumavis replied as I was about to submit my response)

**Comment by dckc** [comment]
:bulb: `endo save-as just-in-case --clear-state`

Is that feasible? that is: take all my current stuff and move it out of the way, but under a name so I can get stuff out of it if I want to.

_pls excuse laziness of not making a new issue_

**Comment by kriskowal** [comment]
(I’m reserving `dump` and `load` right here. We could conceivably have a dump format that allows for partial capture of the formula DAG. Could be pretty simple.)

**Comment by dckc** [comment]
> > 💡 `endo save-as just-in-case --clear-state`
> > Is that feasible? that is: take all my current stuff and move it out of the way, but under a name so I can get stuff out of it if I want to.
> 
> Dumping the internal state of a daemon is feasible and advisable once the structure stabilizes.

`save-as` wasn't intended to be anything like `dump`. More like:

```
$ endo eval 1 -n thing1
$ endo eval 2 -n thing2
$ endo list
thing1
thing2
$ endo save-as closet --clear-state
$ endo list
closet
$ endo show closet.thing1
1
$ endo show closet.thing2
2
```

**Comment by kriskowal** [comment]
Ah, so `save-as` might expand to:

```
$ endo mkdir closet
$ endo mv thing1 closet
$ endo mv thing2 closet
$ endo cancel closet.thing1
$ endo cancel closet.thing2
```

I think by `--clear-state` you might mean `--cancel`, which just throws away the in-memory incarnation but preserves the formula. The formula is in `endo where state`: state in the XDG sense.

**Comment by dckc** [comment]
yes, ... the feature I want is: move everything to a new child.

**Comment by rekmarks** [comment]
It seems like `purge` is a viable candidate, and to that end I created #1989.

**Comment by rekmarks** [comment]
Closing this since #1989 was merged (but did not automatically close this for some reason).

@dckc do you want to create a new issue for "move everything to a new child"?

**Comment by dckc** [comment]
> new issue for "move everything to a new child"

IOU
