### ISSUE TITLE
node -r ses main.js

### ISSUE THREAD

**Issue by DavidBruant** [endojs/endo#209]
Node.js provides [a `-r` option](https://nodejs.org/api/cli.html#cli_r_require_module) which loads a module before running the file. I feel like ses would be a great candidate for this option

To enable ses, people would need to change their `node main.js` into `node -r ses main.js`

**Comment by kriskowal** [comment]
This is a very neat idea. Do you imagine that this automatically calls lockdown? I do imagine that this would automatically call lockdown. Is there a case where someone would want to import ses manually and either not lock down or lock down more than once?

**Comment by erights** [comment]
I like this too. Simple things should be simple. Complex things should be possible. So to answer @kriskowal I think the simple default is that it does call lockdown *and* execute a start script in the start compartment that sets up other compartments for least authority linkage, and then start main.js is one of those POLA compartments. But this requires a policy manifest already exist that is associated with main.js. In the absence, we should have a default fallback policy for exactly this, where the start script starts one new compartment with a very narrow set of endowments, and starts main.js in it.

Variations on this default will still need to be possible.

**Comment by kriskowal** [comment]
We’ll have to look into whether -r modules can detect that they were -r’ed. We could switch on that.

**Comment by warner** [comment]
Would `node -r ses` do the equivalent of `import XYZ from 'ses'`? If we make it call `lockdown()` as a side-effect of import, wouldn't that prevent normal apps from importing `lockdown` instead (and calling it with different arguments), or from modifying primordials (e.g. the metering transform) before `lockdown` freezes them?

If so, maybe we'd need a different name: `node -r ses_start` or something.

**Comment by erights** [comment]
Yeah, I was assuming they were different. `ses_start` sounds good to me.

**Comment by warner** [comment]
hm, to add to the bikeshedding, `start_ses` sounds more grammatical

**Comment by DavidBruant** [comment]
> Do you imagine that this automatically calls lockdown?

Yes

> Simple things should be simple. Complex things should be possible.

yes. that's where i'm coming from with this idea

> But this requires a policy manifest already exist that is associated with main.js

Possibly, it could be in package.json (if `main.js` is what's in the [`main`](https://docs.npmjs.com/files/package.json#main) entry of package.json)

**Comment by kriskowal** [comment]
#411 attempts to address this issue.

**Comment by kriskowal** [comment]
As we’re starting to build out Endo, it’s pretty clear that we’re not building it this particular way. Using `-r` would let us hook the module loader and lockdown, effectively running the following program like a posix process, but there’s a feature gap in how the program gets powerful Node.js built-in modules. If the policy is “none by default”, there is no opt-in mechanism to hook in here. The Endo Application model is likely to more closely resemble “Caplets” of yore, where the Endo application has a manifest describing the capabilities it needs, exports a conventionally named method, and receives an Endo Application Facet in the shape of the described manifest.
