### ISSUE TITLE
daemon: `introduceNamesToParty` should be awaited

### ISSUE THREAD

**Issue by rekmarks** [endojs/endo#2121]
Following #2120, we should ensure that `introduceNamesToParty` is always awaited.

**Comment by rekmarks** [comment]
@kriskowal should introductions be synchronized? They are not currently, but if new parties expect their introduced names to be immediately available, they should be.

**Comment by kriskowal** [comment]
> @kriskowal should introductions be synchronized? They are not currently, but if new parties expect their introduced names to be immediately available, they should be.

I would expect names to be available to the guest the moment the guest is mentionable.
