### ISSUE TITLE
test cover cli demo

### ISSUE THREAD

**Issue by grypez** [endojs/endo#2368]
## What is the Problem Being Solved?

The cli package is [not currently tested](https://github.com/endojs/endo/blob/3e3b8c6059c16c788223586ba01190d70963d61c/packages/cli/package.json#L31). It would be nice to write some tests, and the demo seems like a good place to start.

## Description of the Design

- [x] Activate ava test coverage in cli package
- [x] Create an ava entry point which tests each section in isolation after running `endo purge -f`.

For each runnable section of [the cli demo](https://github.com/endojs/endo/blob/master/packages/cli/demo/README.md), produce a bash script executing that functionality and a log of the expected output of the script, then assert equality of the expected and observed output of the script using diff (for an example see the description of [this issue](https://github.com/endojs/endo/issues/2074#issue-2135049457)).
- [x] A counter example
- [x] Doubler Agent
- [x] Sending Messages
- [x] Names in transit...
- [x] Mailboxes are symmetric
- [ ] Familiar Chat (note UI interaction)
- [x] Running a confined script

### Out of Scope
- Programmatically ensuring that the documented functionality aligns with the tested functionality

**Comment by kriskowal** [comment]
You may have more luck ensuring portability if the tests are framed as Node.js shelling out to the CLI. Execa is popular at Agoric. https://www.npmjs.com/package/execa
