### ISSUE TITLE
bundler option to strip comments

### ISSUE THREAD

**Issue by turadg** [endojs/endo#2413]
## What is the Problem Being Solved?

Endo is often bundled for use in runtime environments that constrain bundle size. Sometimes these bundles exceed the limits (e.g. https://github.com/Agoric/agoric-sdk/issues/9900).

A significant source of bytes is comments. If comment could be stripped at the discretion of the builder of the bundle, that would reduce the size significantly.

E.g. in a recent contract bundle the `patternMatchers.js` file was 59KB. That’s a little less than the raw 62KB of [the source in Endo](https://github.com/endojs/endo/blob/%40endo/patterns%401.4.2/packages/patterns/src/patterns/patternMatchers.js)
but still quite a lot more than it would be without comments. [Terser with defaults](https://try.terser.org/) drops it to 19KB. If we cut Endo dep size to 1/3 or even 2/3 we’d buy a lot more time on bundle size limits.

## Description of the Design

Provide an option to the `bundle-source` command to turn comments to whitespace.

It should preserve line numbers so that stack traces in runtime match up with the original source code. However it does not need to preserve character positions per line.

Unlike conventional minifiers, it should not perform any alterations to the actual code,
- https://github.com/endojs/endo/issues/2117 

While implementing this, it may be helpful to consider how one would extend it to
- https://github.com/endojs/endo/issues/2415

## Security Considerations

Stripping comments can make it harder to audit the bundled code. But conversely, comments can mislead in an audit.

Given the complexities of audits and the trade-offs with runtime constraints, solving auditing will require purpose-built tooling: https://github.com/endojs/endo/issues/1656

**Comment by mhofman** [comment]
> Provide an option to the `bundle-source` command to turn comments to whitespace.

Quick note that striping comments requires in some case to insert a semi colon to preserve the semantics of ASI. It's not always purely replacing with whitespace.

**Comment by kriskowal** [comment]
My intention is to replace the interior of comments: erase all characters before newlines, replace all characters on the final line with spaces, preserve all newlines. That covers @gibson042’s subtle case of comments containing newlines serving as newlines for ASI.
