### ISSUE TITLE
support .ts in bundle-source

### ISSUE THREAD

**Issue by turadg** [endojs/endo#2415]
## What is the Problem Being Solved?

TypeScript is very popular and the JsDoc syntax for it has many limitations compared to .ts. (Some described in https://github.com/Agoric/agoric-sdk/issues/5760) 

A developer who wants to write in `.ts` can transpile before bundling with Endo, but that increases work, room for error, and the transformation chain to audit. 

## Description of the Design

bundle-source would bundle `.ts` files directly by transparently transforming them to .js using something like https://bloomberg.github.io/ts-blank-space/ or `@swc/wasm-typescript` used in Node's new .ts support.

## Security Considerations

Transforming code can make it harder to audit the bundled code. But conversely, type annotations can mislead in an audit.

Given the complexities of audits and the trade-offs with runtime constraints, solving auditing will require purpose-built tooling: https://github.com/endojs/endo/issues/1656

**Comment by mhofman** [comment]
Striping TS types and purely replacing with whitespace may cause semantic JS difference, and some cases need special handling. Any mechanism that support TS in bundle source need to correctly handle these cases and not change the runtime semantics.

Some pointers:
- [Effects of types on ASI](https://gist.github.com/acutmore/27444a9dbfa515a10b25f0d4707b5ea2)
- [TS syntax can also be valid JS syntax](https://github.com/microsoft/TypeScript/issues/33639), in particular the [3rd comment](https://github.com/microsoft/TypeScript/issues/33639#issuecomment-2291568328) showing that experimental type erasure in Node.js results in different runtime semantics.

**Comment by kungfooman** [comment]
Pure ESM has so many advantages... just being able to do `<script type="module" src="..."></script>` with an import map... TS destroys nice ESM and also makes code unreadable. Simple one liner JS functions that are easy to document with JSDoc become type monsters where you can't even differ between real code and type sugar any longer without starring at ASCII soup for 5 minutes.

For what? The beginning of the end.

**Comment by turadg** [comment]
This in TS 5.7 might help,
- https://github.com/microsoft/TypeScript/issues/59597

And this may be a better option than the WASM:
- https://bloomberg.github.io/ts-blank-space/
