### ISSUE TITLE
Permit Promise.try

### ISSUE THREAD

**Issue by kriskowal** [endojs/endo#2607]
## What is the Problem Being Solved?

Promise.try ships with Node.js 23 and is now Stage 4. SES should permit it.

## Description of the Design

Add and allow in SES permits

## Security Considerations

Permit.try is safe to share

## Scaling Considerations

None

## Test Plan

None

## Compatibility Considerations

Backward compatible

## Upgrade Considerations

None

**Comment by erights** [comment]
See https://github.com/tc39/proposal-promise-try
