### ISSUE TITLE
Add allowUnsafeSources option to Compartment constructor

### ISSUE THREAD

**Issue by michaelfig** [endojs/endo#261]
> define a flag like allowUnsafeSources: ['htmlComments', 'directEval', 'importExpressions'] so that the creator of a Compartment can specify that those parts of the default (assertions) transforms are not necessary.
> — https://github.com/Agoric/SES-shim/issues/261#issuecomment-613684965

---

Since these may be within quoted strings or template literals, we should at least emit a warning with line numbers. My preference would be an error by default, with some option needed to proceed despite detecting one of these.

_Originally posted by @erights in https://github.com/Agoric/agoric-sdk/pull/898_

**Comment by erights** [comment]
Clever idea. If we can figure out some test like that which reliably indicates a syntax error, then yes.

However the specific test you suggest is only true for `{` in an expression context. A `{` that starts a block would evade your test and thus circumvent the prohibition.

**Comment by michaelfig** [comment]
> However the specific test you suggest is only true for `{` in an expression context. A `{` that starts a block would evade your test and thus circumvent the prohibition.

Aaagh!

How about `@[a-z]+ \{import\(`?

**Comment by erights** [comment]
Is that exactly one space? That seems safe but restrictive. Be aware that there is an active decorator proposal for adding annotations to JS classes/methods/fields where a decorator can begin with `@[a-z]+`. Once the syntax for that settles down, we should revisit this rule.

How can we ensure that we revisit this rule before decorators become real?

**Comment by erights** [comment]
The reason I ask about the "exactly one space" is, on the one hand, it seems overly restrictive. On the other hand, if we accept more whitespace, we must *not* accept whitespace that includes a newline, as ASI might turn that newline into a semicolon.

**Comment by michaelfig** [comment]
Is `^\s+\*\s+@[a-z]+\s+\{import\(`, where `\s` only matches spaces and tabs, legitimate decorator syntax?  I.e. can decorators be used as an argument to multiply?

**Comment by michaelfig** [comment]
Or more specifically, can decorators adorn blocks?

**Comment by michaelfig** [comment]
In conversation with @erights, no, decorators cannot adorn blocks.

I do propose that we add a condition only so that the JSDoc pattern given [above](https://github.com/Agoric/SES-shim/issues/261#issuecomment-612292790) is allowed, and explicitly documented as such in SES.

**Comment by michaelfig** [comment]
@kriskowal would you please have a look at the above PR (https://github.com/Agoric/realms-shim/pull/124) and merge it to the new SES-shim?

**Comment by michaelfig** [comment]
@kriskowal

We should not land the above ad-hoc hack, as @Jack-Works asserted.

Instead, define a flag like `allowUnsafeSources: ['htmlComments', 'directEval', 'importExpressions']` so that the creator of a Compartment can specify that those parts of the default (assertions) transforms are not necessary.

Then, they can set their own transforms to fix up the sources that the default transforms would have ordinarily rejected.

**Comment by erights** [comment]
@Jack-Works where is the message @michaelfig refers to above, about why we should not land this?

**Comment by Jack-Works** [comment]
> @Jack-Works where is the message @michaelfig refers to above, about why we should not land this?

https://github.com/Agoric/realms-shim/pull/124#issuecomment-612711306

**Comment by erights** [comment]
See https://github.com/Agoric/agoric-sdk/issues/958#issuecomment-615552446 for safety constraints on how we solve this problem.

**Comment by michaelfig** [comment]
This issue can be solved by preprocessing and rewriting comments in the source code before sending it to SES.  I'm closing the issue, as SES doesn't need to change.  See Agoric/agoric-sdk#958 for details, and https://github.com/Agoric/agoric-sdk/blob/23c426916c66b2c79c607a4efda324dbbb8aacd5/packages/bundle-source/src/index.js#L137 for an implementation that works.

**Comment by kriskowal** [comment]
Thanks for the reference @michaelfig. It’s timely!
