### ISSUE TITLE
"Learn how to use SES in your own project." links to empty docs

### ISSUE THREAD

**Issue by paul90** [endojs/endo#267]
The "Learn how to use SES in your own project." link in the readme links to empty docs. 

Maybe it should link to the docs from `SES-shim/packages/ses/docs/`, as the link in the readme there also goes to the same place.

**Comment by kriskowal** [comment]
Thank you for filing. We will have to revisit the docs and fix this hole.

**Comment by paul90** [comment]
Any chance this is lack of documentation is ever going to be addressed?

**Comment by paul90** [comment]
Going to close this as #742 is a recent duplicate.
