### ISSUE TITLE
Clarify the behavior of defineProperty

### ISSUE THREAD

**Issue by jfparadis** [endojs/endo#30]
Referencing https://github.com/tc39/proposal-realms/issues/141 by @erights:

Because of the weird semantics of the browser's Window vs WindowProxy (not a proxy btw), the spec of `Object.defineProperty` was changed to allow it to indicate failure by returning false rather than throwing. The `defineProperty` exported by commons.js should wrap this to turn this false result back into a thrown error.

See also https://github.com/tc39/ecma262/issues/672

Needs a safety label

[edit 2020-09-15 @kriskowal]:

- Some browsers currently: defineProperty always throws and sometimes violates object invariants to force success. The relevant circumstance is only on the `WindowProxy`, not `Window`, due to navigating frames.
- [ ] The spec: proposal: defineProperty must obey object invariants and may indicate failure by returning false.
- [ ] Verify: The shim and the SES spec: After `lockdown` repairs, defineProperty only indicates failure by throwing (and always fails when it cannot succeed without breaking object invariants)
- [ ] The SES lockdown spec: capture above in specification language.

**Comment by kriskowal** [comment]
The shim now also tames `Object.defineProperty` by internally using `Object.defineProperties`, bypassing the aberrant behavior. Closing as fixed.
