### ISSUE TITLE
`with (scopeProxy) { foo() }` leaks scopeProxy if foo mentions `this`.

### ISSUE THREAD

**Issue by erights** [endojs/endo#31]
Typing `valueOf()` into the evaluator shim playground (demo/index.html) and hitting the Evaluate button causes the error

> please report internal shim error: unexpected scope handler trap called: ownKeys

Unlike other surprising scopeProxy traps, this does not look like an engine bug. We see identical symptoms on Brave, FF, and Safari.

[edit by @kriskowal 2020-08-12:]

Actions needed (to be independently tracked, and this issue closed)

- ~~Create a specification proposal that introduces a `hiddenWith` symbol that `with` would respect.~~
- [ ] Document this known-limitation of SES-shim, ~~barring eventual engine support for a `hiddenWith` symbol.~~
- [ ] Confirm that ~~absent `hiddenWith`,~~ revealing the `ScopeProxy` does not break containment.

**Comment by dckc** [comment]
This is a _use_ of `this`, not a _mention_ of `this`, no?

> ```js
> ...
> function foo() { return this; }
> ...
> ```

**Comment by erights** [comment]
Well, it is also a mention of `this`. But good point. I genuinely do not know what the least confusing short title would be. "Uses `this`" can be misunderstood in other ways (such as "uses the value that `this` evaluates to"). I'll just let these notes in this issue thread clarify, and leave the title as is. Thanks.

**Comment by dckc** [comment]
> Well, it is also a mention of `this`.

Ah. I see. Thanks.

**Comment by mhofman** [comment]
We've noticed that some Web APIs such as `fetch` are sensitive to the `this` / context. If it's null-ish or a real `window` object, it works fine, but fails with a `TypeError` if any other object: `Failed to execute 'fetch' on 'Window': Illegal invocation` (message on v8/Chrome) or `'fetch' called on an object that does not implement interface Window` (message in SpiderMonkey/Gecko).

This fidelity bug of the shim causes code that would otherwise work to break.

**Comment by erights** [comment]
How has multi-backflip affected this?

**Comment by mhofman** [comment]
It still leaks, but only the `globalThis` regular object.

Main problem left is for module lexical created by the shim, as detailed in #912.

Should we rename the title of this issue? It might be good to keep tracking an engine level change allowing to disable the current with context behavior.

**Comment by erights** [comment]
> Should we rename the title of this issue?

Please do!

**Comment by kriskowal** [comment]
Narrowed scope and posted for follow-up: https://github.com/endojs/endo/issues/1954
