### ISSUE TITLE
Create documentation for `harden`

### ISSUE THREAD

**Issue by kriskowal** [endojs/endo#320]
There is no documentation in harden, make-harden, or SES that dives into the details:

* the fringe
* the prototype check

We need this and also links back to that documentation in SES, make-harden, and harden.

**Comment by dckc** [comment]
Take care that we're clear on documenting an API vs. an implementation.

> In discussion with @jfparadis , he concurred that the whole business of tracing frozen stuff with a WeakMap is kinda silly in xs where so much stuff is frozen to start with. In particular, this optimization of not hardening prototypes is a noop on xs, since the prototypes will already be frozen. This test seems to be testing an implementation detail, not a feature.
https://github.com/Agoric/SES-shim/issues/104#issuecomment-569477910

**Comment by kriskowal** [comment]
These details have been simplified away and no longer require documentation.
