### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by andrwo** [endojs/endo#332]
Hi, I am trying to use this library to evaluate some simple user-entered JS code safely against some object context in node.js and came by this interesting project. But how do you use this?

The links for "Learn how to use SES in your project" does not work. The rawgit demo is a dead link. Googling for ses seems to give old code using SES.makeSESRootRealm() that seems obsolete. The docs folder in /ses/docs/ seems to be of the old module usage too (without Compartments).

Frankly, quite bewildering for those not really knee deep in the intricacies of (un)safe javascript ..., I'm just looking for a simple "eval" against a object with minimal primodials. :D

**Comment by russtoku** [comment]
After you click on the [Learn how to use SES in your own project](https://ses-secure-ecmascript.readthedocs.io/en/latest/) and you get to that page, click on the ```Read the Docs``` line at the bottom left part of the page. It should pop up more info where you can click on the link to the [stable version](https://ses-secure-ecmascript.readthedocs.io/en/stable/) of the docs. I think that should help until things can get fixed up to point to the latest version of the docs.

The reorganization of several repos into the SES-shim one appears to have broken things hosted on Read the Docs.

**Comment by andrwo** [comment]
Thanks for getting back!

I tried the latest stable (0.6.5) that uses SES.makeSESRootRealm(...), which works fine when imported into nodeJS, but I can't get it to compile in ReactJS- not playing nice with webpack. It gives a "ReferenceError: _createclass is not defined" error.

I gave the latest dev version a go, which I understand is geared towards a future where this is built into EcmaScript itself, but for now, using "import 'ses'" as a shim.

I got what I wanted working in both NodeJS and ReactJS:
```
import "ses";
// lockdown();
const c = new Compartment({a: 2});
console.log( c.evaluate("a+a") );  // displays 4
```
However, I am a bit confused over usage of lockdown(). Once I used the lockdown(), the freezing and disabling of Maths.random, Date.now() etc killed my application. Do I really need to perform the lockdown(), especially at my root realm where my entire application lives? What I really wanted is to instantiate a very 'safe' Realm and evaluate JS code in that Realm given some (safe) context like { a: 2 }.

**Comment by russtoku** [comment]
The [README.md](https://github.com/Agoric/SES-shim/tree/master/packages/ses) for Secure EcmaScript (SES) might help. The content is the same for the [module on NPM](https://www.npmjs.com/package/ses). See also [Secure Coding Guidelines under SES](https://github.com/Agoric/SES-shim/blob/master/packages/ses/docs/secure-coding-guide.md).

Apologies, I just became aware of SES last week when I watched Kate Sills' QCon presentation, [Making Npm Install Safe](https://www.infoq.com/presentations/npm-install/). I'm still trying to understand things.

**Comment by phyllisstein** [comment]
Took a while to find the most up-to-date documentation through trial and error, but it looks like [`ses-0.7.md`](https://github.com/Agoric/SES-shim/blob/master/packages/ses/docs/ses-0.7.md) describes the non-Realms API currently supported. I can't say for sure, but my understanding is that it was changed due to security vulnerabilities in the Realms shim. [Figma reported a related issue](https://www.figma.com/blog/an-update-on-plugin-security/) about a year ago.

**Comment by kriskowal** [comment]
This issue predates considerable changes to the answer to the original question which I believe are answered in the current README. Please feel free to reopen this or start a conversation on our mailing list! https://groups.google.com/g/ses-strategy
