### ISSUE TITLE
Need clearer POLA layering between the shim core and the module support

### ISSUE THREAD

**Issue by erights** [endojs/endo#373]
The shim core goes from the 8 magic lines of code out to `compartment.evaluate`. This is our security kernel in that everything is potentially vulnerable to a bug in the core. Therefore the core should be clearly distinguished from the rest, as extremely simple as possible, and small.

The module portion of the SES shim should be built on top of this, such that a bug in the module support code leads only to bounded damage.

https://github.com/Agoric/SES-shim/blob/817fe1a7e320d4f9cc4a526b548ef639f172feb8/packages/ses/src/module-instance.js#L303

violates this, in that the module support code has access to the `realmRec` giving it unlimited ability to cause damage. Rather, perhaps the `performEval` it should by given access to is one that already curries over the `realmRec`. The rest of `performEval` seem like exactly the POLA powers that the module support code should get.

**Comment by erights** [comment]
Note that this curried `performEval` is still more power than the public SES API, so the module code is not to be "layered on top of SES". Rather, both SES and modules are layered on top of core SES, which is not otherwise exposed.

**Comment by kriskowal** [comment]
@erights, I believe you satisfied this issue by erasing mention of realm records in the relevant evaluator code. Please reopen if the issue remains.

**Comment by erights** [comment]
We're a lot closer, but it is still not easy to see the line between the two layers. Reopening.

**Comment by erights** [comment]
@kriskowal is this a duplicate of #454 ?

**Comment by kriskowal** [comment]
Close enough to close as a consequence of the same work. The module layer now uses `compartment.evaluate`, with a non-standards-track `__moduleShimLocals__` option to thread property descriptors for the scope proxy.
