### ISSUE TITLE
Precompile whole archived applications

### ISSUE THREAD

**Issue by kriskowal** [endojs/endo#413]
As mentioned in #412, SES currently entrains a JavaScript parser transform framework (Babel) to faithfully emulate `Compartment.import`. However, this expands the size of SES from about 32KB to about 3MB, two orders of magnitude.

It should be possible to precompile whole applications using the same ESM-to-program transform that SES-shim’s Compartment implements internally. An archived application would capture the compiled JavaScript programs for every module, a JSON representation of their linkage, and conceivably also other resources.

This would be a more advanced archive than an archive that merely captures the sources of every module and performs analysis, load, and link at runtime, and require a thinner runtime.

**Comment by erights** [comment]
@kriskowal is this the endo packager/bundler?

**Comment by kriskowal** [comment]
Suffice it to say, this is done.

Precompiler ~#673~

Bundler ~#296~

Bundler PR ~#707~ Issue ~#175~
