### ISSUE TITLE
Intermittent getOwnPropertyDescriptor scope handle trap while debugging

### ISSUE THREAD

**Issue by FUDCo** [endojs/endo#429]
In the course of diagnosing a (hopefully unrelated) problem, I've been experiencing random occurrences of the message `please report internal shim error: unexpected scope handler trap called: getOwnPropertyDescriptor` showing up in the console log.  This is happening as I'm stepping around in the Chrome debugger attached to a Node process running on OSX.

This behavior is intermittent, seems to happen at random, and I have not found a way to reliably reproduce it.  It appears to happen when I'm running from one break point to another, as one must do when debugging async code that does not allow for single stepping.  Aside from the messages appearing in the console log, it does not appear to abort any computation of note, even though I am given to understand that this message is being produced by an `assert` call.

Ref #428 @erights @kriskowal

**Comment by diachedelic** [comment]
![image](https://user-images.githubusercontent.com/310464/91976132-dc318700-ed63-11ea-9341-52e22499e931.png)

**Comment by erights** [comment]
I don't think this is a live problem anymore but am not yet sure enough to close.

**Comment by erights** [comment]
Closing as a dup of the already-closed https://github.com/endojs/endo/issues/1510
