### ISSUE TITLE
StaticModuleRecord: test exact string of generated functor

### ISSUE THREAD

**Issue by jfparadis** [endojs/endo#47]
This transform is largely dependent on the output of Babel: any change in Babel can have an impact on the security of the transform, depending on the environment where this is run.

Currently most of the intended transforms are documented in https://github.com/endojs/endo/blob/master/packages/static-module-record/REWRITE.md

I have also added the output of some tests in https://github.com/endojs/endo/blob/master/packages/static-module-record/TESTS.md

However, there is no test to control and validate that Babel executes those transforms. Changes in Babel will not be detected, unless it breaks integration.

**Comment by kriskowal** [comment]
Such tests now exist.
