### ISSUE TITLE
Subsume globalThis shim

### ISSUE THREAD

**Issue by kriskowal** [endojs/endo#479]
Add the creation of `globalThis` to the lockdown shim.

Per https://github.com/Agoric/SES-shim/pull/468/files#r492227968

**Comment by erights** [comment]
@kriskowal can this be closed?

**Comment by kriskowal** [comment]
No, I don’t believe we’ve done this yet, and I still think we ought to. @kumavis can confirm.

**Comment by erights** [comment]
What's the minimal JS we are still trying to support? On this minimal version, does `globalThis` still need to be shimmed, or can we now just depend on it?

**Comment by kriskowal** [comment]
`globalThis` support begins at Node.js 12, which is where principled SES support begins. In practice, LavaMoat is on 10.

**Comment by kriskowal** [comment]
@kumavis Any opinion on whether we should continue pursuing this stale ticket?

**Comment by kumavis** [comment]
![image](https://github.com/endojs/endo/assets/1474978/c4d855de-2bdb-44b6-9630-7230451c25c1)

well supported and shim is trivial -- fine to close

https://caniuse.com/mdn-javascript_builtins_globalthis
