### ISSUE TITLE
Need no-op console setting for determinism

### ISSUE THREAD

**Issue by erights** [endojs/endo#487]
As explained at https://github.com/Agoric/agoric-sdk/issues/1852 . That issue, in `agoric-sdk`, is about the SwingSet portion of incorporating this into deterministic replay. This issue is about the actual console mechanism that would support that without being at all specific or cognizant of SwingSet.

**Comment by kriskowal** [comment]
I believe this to be addressed for Agoric’s needs by way of a deterministic console shim.

**Comment by erights** [comment]
Do we have such a console shim? If not, why close this?

**Comment by kriskowal** [comment]
We do. XSnap bootstrap for vats includes a deterministic console shim. Attn @michaelfig for the confirmation. Please reöpen if I’m mistaken that the need has been addressed.

**Comment by mhofman** [comment]
Correct: https://github.com/Agoric/agoric-sdk/blob/ba2f0d94e904cef1fdbf93c84a81fdf7005fb3be/packages/xsnap-lockdown/lib/object-inspect.js
