### ISSUE TITLE
Restore CommonJS to CompartmentMapper

### ISSUE THREAD

**Issue by kriskowal** [endojs/endo#501]
#500 removes support for CommonJS from Compartment Mapper to eliminate a dependency on Babel that interferes with RESM+Rollup by capturing a dependency on the Node.js readable stream built-in-module.

To get CommonJS back, it might be better to borrow @guybedford’s lexer, convert it to ESM, and teach it to discover static requires in addition to exports and reexports:

https://github.com/guybedford/cjs-module-lexer/blob/master/lexer.js

**Comment by guybedford** [comment]
There is already a PR to capture static requires in https://github.com/guybedford/cjs-module-lexer/pull/10.

Please be my guest in forking and using that further.
