### ISSUE TITLE
Migrate Agoric-SDK packages (Endo-0)

### ISSUE THREAD

**Issue by kriskowal** [endojs/endo#506]
- [x] ~acorn-eventual-send~
  - [x] ~assert~
  - [x] bundle-source
  - [x] captp
  - [x] eventual-send
  - [x] far
  - [x] import-bundle
  - [x] ~import-manager~
  - [ ] ~install-metering-and-ses~
  - [x] install-ses
  - [x] marshal
  - [ ] notifier
  - [x] promise-kit
  - [ ] same-structure
  - [ ] store
  - [x] ~tame-metering~
  - [x] ~transform-eventual-send~
  - [x] ~transform-metering~
  - [ ] weak-store
  - [x] base64

Per https://docs.google.com/spreadsheets/d/1-gSPlAqFZYw9QHyYuCYubSNjyLN00JxtWcqT9hjEvBc/edit#gid=0

**Comment by dckc** [comment]
The current alpha plan clearly entails moving `bundle-source`, `import-bundle`, and their dependencies. It's not clear to me that it requires moving `@agoric/capttp`, `@agoric/store` and such. Perhaps moving `bundle-source` and `import-bundle` is a subgoal worth splitting out?

p.s. how did you generate the dependency diagram, @kriskowal ?

**Comment by dckc** [comment]
@erights - for Lavamoat - is splitting out the distributed computing stuff useful?

**Comment by erights** [comment]
I don't think splitting it out is useful. Rather, it is postponable because their need for it is less urgent than for local endo.

**Comment by kriskowal** [comment]
I plan to migrate the following from the leaves to the roots in short order, in preparation for adding my endo daemon prototype to this repository.

- import-bundle
  - bundle-source
  - install-ses
- bundle-source
  - lockdown
- captp
  - install-ses
  - eventual-send (not handled-promise-shim)
  - marshal
- far
  - eventual-send (for E only)
  - install-ses (for handled-promise-shim)
  - marshal
- install-ses
  - eventual-send (just handled-promise-shim)
  - lockdown
- marshal
  - eventual-send (shim for tests, E otherwise)
  - lockdown
- eventual-send
  - lockdown
- lockdown

**Comment by kriskowal** [comment]
And @michaelfig and I intend to perform the refactoring of eventual-send-shim from HandledPromise to Promise.delegate in this repository. We can defer breaking changes in two ways: HandledPromise can be reimplemented in terms of Promise.delegate and we can have a temporary `@endo/eventual-send-shim` that exports `@endo/eventual-send/shim.js`.

**Comment by kriskowal** [comment]
I’m calling this completed for this round, since I believe I have everything I need to make the first cut of Endo interesting. I can move some of the other packages opportunistically, and we will need another phase of migrations to bring over SwingSet or XSnap.
