### ISSUE TITLE
Endo Alpha: Snaps are able to use bundleSource and importBundle

### ISSUE THREAD

**Issue by kriskowal** [endojs/endo#514]
goal: Snaps are able to use bundleSource and importBundle.

_EDIT: planning outline moved to milestone(s)_

**Comment by dckc** [comment]
@kriskowal I'm used to working in terms of telling a story that explains what the world looks like when this thing is available... the smallest useful version of this thing. I'm struggling to understand what that story looks like.

Who is our protagonist that wants this thing? What are they trying to do? How do they do it with this thing?

I propose some ground rules:
  - concrete terms only. No "foo" and "bar"
  - one path through the story; no "can do this or can do that"

ref [StoryTellingAndTestCases](https://informatics.gpcnetwork.org/trac/Project/wiki/StoryTellingAndTestCases)

**Comment by dckc** [comment]
goal: Snaps are able to use bundleSource and importBundle.

This is a high-level goal / story we came up with in a recent meeting.

**Comment by dckc** [comment]
> restore cjs in cm with lexer (or eradicate commonjs dependency from kernel)

This is one of the few bullet points that doesn't cite an issue. A quick search of issues doesn't turn up any obvious candidates. Is this still worth doing? If so, care to elaborate in an issue, @kriskowal ?

**Comment by dckc** [comment]
In response to a question from @rowgraus , I just explained:

Snaps are MetaMask plug-ins. bundleSource is how we package up Agoric contracts. it currently uses rollup (ew). The goal is (a) it uses endo, and (b) not only Agoric but also MetaMask can use this bundling mechanism. (they currently use something closely related). Benefit: reduce runtime supply-chain risks.

I propose to add that to the description of this issue.

**Comment by kriskowal** [comment]
Closing. We achieved “Endo Alpha” in the `endo` branch some time ago. That is, a “caplet” (née Snap in this issue’s dated parlance) can be loaded into a worker in the Endo pet daemon. We went on to also support unsafe caplets, and same-origin isolated weblets.
