### ISSUE TITLE
SES shim testing on XS: "tiny ava"

### ISSUE THREAD

**Issue by dckc** [endojs/endo#535]
@kriskowal , @erights , my previous work is https://github.com/agoric-labs/tape-xs last revised Jan 27 0fbe38c

Fortunately, I was on my game back then and made a nice README, complete with limitations and such. I think I even got @michaelfig to review it, so he may remember a little bit about it.

(for my reference: see also https://github.com/Agoric/agoric-sdk/issues/370 , https://github.com/Agoric/agoric-sdk/issues/49 )

**Comment by dckc** [comment]
## `ava-xs` from agoric-sdk modified to run SES tests in pre-lockdown compartment

`ava-xs` runs test scripts each in its own `Compartment`. It was originally developed to run tests in `agoric-sdk`. It intercepts `import 'ses'` and provides basically a noop, since it loaded the [xsnap SES bootstrap](https://github.com/endojs/endo/blob/535-ava-xs/packages/xsnap/lib/ses-boot.js) into each compartment before starting the test script:

```js
import './console-shim';
import './text-shim';
import '@agoric/eventual-send/shim';
import './lockdown-shim';

harden(console);
```
(We run this thru rollup and then `xsnap.evaluate()` it.)

In #650, I copied `ava-xs` from to the endo repo, planning to eventually move it.

But running the SES tests in a locked down SES compartment was a mess.

So after bouncing ideas around with @kriskowal , I came up with [ses-test-env-debug.js](https://github.com/endojs/endo/blob/535-ava-xs/packages/xsnap/lib/ses-test-env-debug.js):

```js
import './console-shim';
import './text-shim';
import 'ses/lockdown';
```

Note in particular that `import 'ses/lockdown'` does _not_ call `lockdown()` the way `import './lockdown-shim'` does in the agoric-sdk SES bootstrap above.

This allows us to run SES tests that only need `ses/lockdown`; i.e. those that don't need `module-shim`, which depends on `babel`. (https://github.com/endojs/endo/issues/508#issuecomment-817198575 has details on why we currently exclude some others)

### Running agoric-sdk tests in a pre-lockdown compartment

This seems relatively straightforward in theory, but I'm leery of taking it on as it was no mean feat to satisfy the constraints to run the current set of agoric-sdk tests on `ava-xs` and I can imagine various practical details turning up as we shift the constraints under the whole set of tests.

In particular, I expect `import 'ses'` should be replaced by `import 'ses/lockdown'` in dozens of places, and `@agoric/import-ses` may need to split into layers depending on whether `module-shim` is required.

cc @erights @kriskowal @warner @michaelfig

**Comment by erights** [comment]
Hi @dckc is this done?

**Comment by erights** [comment]
If the point is the pre-lockdown, nevermind. Is this something we need?

**Comment by dckc** [comment]
I believe we want to run the SES test suite on XS (#508); for that, we need something like ava-xs in the endo repo. Most likely by moving it from agoric-sdk as part of #681 . I'm using this issue to track that need.

**Comment by kriskowal** [comment]
We’re pursuing XS parity testing with test262 style tests instead of Ava. #812 #1847.
