### ISSUE TITLE
Shipping an autonomous prototype pollution solution

### ISSUE THREAD

**Issue by DavidBruant** [endojs/endo#544]
I see the ses-shim repo has received its [`ini` bump "security" PR](https://github.com/Agoric/SES-shim/pull/542)

It relates to a prototype pollution vulnerability

Prototype pollution vulnerabilities are common. Only in 2020:
- https://www.npmjs.com/advisories/1573
- https://www.npmjs.com/advisories/1542
- https://www.npmjs.com/advisories/1523
- https://www.npmjs.com/advisories/1515
- https://www.npmjs.com/advisories/1508
- https://www.npmjs.com/advisories/1506
- https://www.npmjs.com/advisories/1502
- https://www.npmjs.com/advisories/1500
- https://www.npmjs.com/advisories/1484
- https://www.npmjs.com/advisories/1480
- https://www.npmjs.com/advisories/1479
- https://www.npmjs.com/advisories/1469
- https://www.npmjs.com/advisories/1468
- https://www.npmjs.com/advisories/1463

The `ini` vulnerability was lying around unnoticed [since _at least_ november 2017](https://github.com/npm/ini/commit/738eca59d77d8cfdddf5c477c17a0d8f8fbfe0fd). For sure, there are numerous others

There is a solution to prototype pollution being developed as part of this repo: hardening intrinsics

I feel a solution could be shipped from this repo by isolating this line (and its dependencies) in a dedicated package:

https://github.com/Agoric/SES-shim/blob/85d20629154a55aadf96ca62d1b2622524acfb0e/packages/ses/src/lockdown-shim.js#L175

(arguably, without taming since taming certainly breaks many packages which would decrease adoption)
(arguably, with the override mistake repair, also to prevent breaking packages which would decrease adoption)

The benefit of this new package would be to be protected from all prototype pollution vulnerabilities (known and yet unknown, past, present and future). It could be promoted by npm security and github security teams anytime there is a new prototype pollution vulnerability discovered (which will probably happen 10+ times in 2021 and years to come)

This promotion could lead to people becoming aware of other parts of SES. 

Also, it would also eventually lead to the npm package ecosystem to adapt to runtimes where intrinsics are frozen (because folks will try freezing the intrinsics, notice something break in a dependency and create an issue/send a PR/fork the dependency)

**Comment by kriskowal** [comment]
This describes LavaMoat in most ways and we are going to try to merge LavaMoat into a new tool called Endo that runs Node apps under SES with least-authority linkage among packages, with a compartment per package. The taming levels are now all configurable and we’ll need to surface those in application policies.

Closing this since we’re tracking Endo progress in repository milestones.

Thanks David! We’re going to make this real.
