### ISSUE TITLE
Add AggregateError and Promise.any to whitelist

### ISSUE THREAD

**Issue by erights** [endojs/endo#550]
#549 updates the whitelist to ES2021 including `Promise.any`. Thus it needs to include `AggregateError` as well, since `Promise.any` makes instances of this. However #549 doesn't do this yet since it doesn't fit into the `NativeError` pattern and will need a bit more thought.

**Comment by mhofman** [comment]
A little investigation uncovers https://bugs.chromium.org/p/chromium/issues/detail?id=1379054.

I suspect this issue is likely fixed already in v8.

**Comment by erights** [comment]
Note that @agoric/internal defines and exports a `makeAggregateError` function that, because this issue is unfixed, makes a faux AggegateError instance which is actually a direct instance of `Error` with an extra own `errors` field to emulate an AggregateError instance. This export is used elsewhere in agoric-sdk. 

Fortunately, since we don't treat the exports from @agoric/internal as public API we need to continue to support, after this bug is fixed, we should eventually be able to remove `makeAggregateError` and fix all sites that call it.

**Comment by erights** [comment]
I also see other existing uses of `AggregateError` itself in agoric-cli/src/install.js. I do not understand how this can currently work at all. Obviously, by permitting actual `AggregateError`, we need to be careful not to break this case.

**Comment by erights** [comment]
It works because it branches on the existence of the global. This explains why it currently works. It also means that fixing #550 will cause that code to take a different branch that should work but is probably not yet testable.

Attn @michaelfig who wrote the relevant uses of `AggregateError` in install.js

**Comment by erights** [comment]
Needed due to https://github.com/cosmology-tech/cosmos-kit/blob/b95e2f92585fd12d7532e846b98cd3b757c1acb8/packages/core/src/utils/endpoint.ts#L28

Although @samsiegart currently has a workaround. So less urgent.

**Comment by michaelfig** [comment]
> Attn @michaelfig who wrote the relevant uses of `AggregateError` in install.js

Where is this "install.js" of which you speak?

**Comment by erights** [comment]
https://github.com/Agoric/agoric-sdk/blob/b9ffe482411b63acfaffbbfbbc1eba6bb241808e/packages/agoric-cli/src/install.js#L177

**Comment by michaelfig** [comment]
> https://github.com/Agoric/agoric-sdk/blob/b9ffe482411b63acfaffbbfbbc1eba6bb241808e/packages/agoric-cli/src/install.js#L177

Wow, I totally don't remember ever having used `AggregateError` before!  So I guess that means I don't bring any (remembered) experience to the table.

Maybe I cargo-culted that `allSettled-AggregateError` pattern from somewhere on the web, or from some earlier version of an `endojs` or `Agoric` repo?  Who knows?
