### ISSUE TITLE
After Lockdown, interactive Node REPL goes crazy

### ISSUE THREAD

**Issue by erights** [endojs/endo#553]
See the following screen recording.

https://user-images.githubusercontent.com/273868/103123990-fd7ff100-463a-11eb-80d5-7cb55b1f0d7d.mov

Attn @bmeck Likely a Node bug, but filing here first until I hear from you. Thanks.

**Comment by bmeck** [comment]
Will look later, probably is how REPL is dealing w/ `RegExp.$1` and friends.

**Comment by bmeck** [comment]
Was wrong on cause, but confirmed bug in Node REPL: https://github.com/nodejs/node/blob/master/lib/internal/repl/utils.js#L350 is using a non-safe roundtrip using `util.inspect`. Will try and fix later.
