### ISSUE TITLE
type annotations for Compartment

### ISSUE THREAD

**Issue by dckc** [endojs/endo#583]
target:

 1. its type is exported via [ses/index.d.ts](https://github.com/Agoric/SES-shim/blob/master/packages/ses/index.d.ts) or similar, and
 2. `@ts-check` is turned on in [compartment-shim.js](https://github.com/Agoric/SES-shim/blob/master/packages/ses/src/compartment-shim.js)

#355 was an initial attempt.

**Comment by kriskowal** [comment]
This was fixed by #782.
