### ISSUE TITLE
Bug fix: Revert or refactor evasive transforms

### ISSUE THREAD

**Issue by kriskowal** [endojs/endo#609]
We have `master` in an unreleasable state. We can fix it by either reverting https://github.com/endojs/endo/pull/608 (if we are satisfied with evaluator options as API for the evasive transforms) or by factoring the evasive transforms out of `src/transforms.js` and up to a new `transforms.js` that `package.json` already points to (but does not yet exist).

**Comment by erights** [comment]
My mistake. I saw the exporting and I forgot that we already provide the needed options. I am in favor of reversing #608 . But I'd also like to hear from @kumavis about why they wanted #608 . Depending on the reason, I may change my mind.

@kumavis ?

@kriskowal if you want to proceed with a release but are blocked by this, please reverse and release. If we change our mind, we can redo this after release.

**Comment by kriskowal** [comment]
The next release shouldn’t come until Monday or Tuesday and we don’t have pressure to release at the moment. We have time to make a measured choice.

**Comment by kumavis** [comment]
@kriskowal @erights
oh, i didn't realize there was an option on `Compartment.prototype.evaluate` to perform these transforms.

for at least `browserify-lavamoat` we want to ideally perform the transforms at bundle time, not at run time. tho the performance benefit is likely negligible.
we also ended up needing [an additional transforms](https://github.com/LavaMoat/LavaMoat/blob/f7bb5484f8222a16165992bb9252188f6af2362a/packages/core/src/sourceTransforms.js#L11-L17) so it was convenient to do it all in the same place

**Comment by erights** [comment]
Instead of the additional transform, could you instead
```js
({ __rejectSomeDirectEvalExpressions__: false })
```
?
Unlike the other rejections, this one is not mandatory since it is not enforcing a safety property. So rather than evading it, we allow you to simply suppress it.

**Comment by erights** [comment]
> tho the performance benefit is likely negligible.

Since we're both just doing this regexp-based, yeah I think it is likely negligible. Please let us know if it seems otherwise.

**Comment by erights** [comment]
See https://github.com/endojs/endo/blob/master/packages/ses/error-codes/SES_EVAL_REJECTED.md

**Comment by kumavis** [comment]
why is the current state unreleaseable?
i think its useful to have access to the transforms without evaluating them

**Comment by rekmarks** [comment]
👋 
For Snaps, we have found that some users have to add their own transforms in order for SES to evaluate their scripts, and we will require those transforms to be applied at bundle time, before the Snap is distributed. As such, it would be nice if _all_ transforms could be applied at bundle time by importing SES's transforms.

**Comment by kriskowal** [comment]
So, assuming we roll forward instead of rolling back, to be releasable, we need to move some of the exports of `src/transforms.js` into a `transforms.js` (not `src/*`, which does not yet exist). There’s already a reference to that file in `package.json`. The top-level `transforms.js` should only export intentionally public API.

There are some internal methods in `src/transforms.js` that need to stay there because they are only useful internally.

**Comment by erights** [comment]
I have no objection to rolling forward.

@rekmarks I am curious what those other transforms are and why they're needed?

**Comment by rekmarks** [comment]
> @rekmarks I am curious what those other transforms are and why they're needed?

@erights, I've yet to determine why, although this is the example I had in mind when I wrote my previous comment: https://github.com/NodeFactoryIo/snaps-cli/blob/3618c98/src/build.js#L156-L162

While working with [NodeFactory's Filecoin snap](https://github.com/NodeFactoryIo/filsnap), I found that SES evaluates the snap script successfully with those transforms, but not without them. I've yet to determine whether all or some of them are necessary for the Filecoin snap.

For context, NodeFactory were contracted in 2019/2020 to write snaps for Polkadot and Filecoin using the original version of our snaps beta. They forked our `snaps-cli` package, and added the above transforms and some other features they wanted.

I'd love to discuss this further during the next SES/LavaMoat call.

**Comment by erights** [comment]
```js
  bundleString = bundleString.replace(/self/g, "window");

  // filecoin specific fix
  bundleString = bundleString.replace(/stdlib./g, '');
```
Guessing what's going on, would it work to alias the global object instead of transforming the code:

```js
const c = new Compartment(...whatever...);
c.globalThis.window = c.globalThis.stdlib = c.globalThis;
```


```js
  // polkadot specific fix, remove setImmediate
  bundleString = bundleString.replace("setImmediate(() => resultCb(result))", "resultCb(result)");
```
This changes the scheduling of the call to `resultCb(result)` from eventually, in a later turn, to now. They can't both be right. If the "now" answer is right, the original probably has a bug and your should push this fix upstream. If (as I suspect) "eventually" is right, then this transform is probably introducing a bug. How does the code fail without the transform?
