### ISSUE TITLE
ses-ava support for t.log

### ISSUE THREAD

**Issue by dckc** [endojs/endo#611]
from https://github.com/Agoric/agoric-sdk/pull/2582#discussion_r594347491 ...

[our tests aren't supposed to console.log](https://github.com/Agoric/agoric-sdk/wiki/agoric-sdk-unit-testing#patterns). `t.log` would be silent unless `ava -v` were used...

```js
    t.log('expected failure', reason);
```

but it's not integrated with the SES console, so we get the boring...

```
  ✔ ses-ava-reject-deep-stacks › ses-ava reject console output
    ℹ expected failure TypeError {
        message: 'msg (a string)',
      }
```

**Comment by erights** [comment]
The boringness should be fixed by https://github.com/endojs/endo/pull/2109

Whatever Ava's properties around quieting or verbosifying `t.log`, #2109 should preserve them. However, from my own testing of raw Ava I am not seeing that silence.

**Comment by dckc** [comment]
The "silent unless -v" aspect of ava went away in some version a while ago, IIRC.

**Comment by gibson042** [comment]
> The "silent unless -v" aspect of ava went away in some version a while ago, IIRC.

Yeah, looks like it was dropped as part of version 4: https://github.com/avajs/ava/commit/0a6e2df467f35256bbf9d855a4cc9ebda0646909
