### ISSUE TITLE
SES - Function constructor this-value

### ISSUE THREAD

**Issue by kumavis** [endojs/endo#615]
is it possible to safely preserve this strict-mode behavior in SES? its a common pre-globalThis pattern
as long as the globalThis is the compartment globalThis, it seems fine :thinking: 
```js
new Function('return this')() === globalThis
```

**Comment by erights** [comment]
Not by any reasonable means. 

I suppose you could do a prior static transform replacing exactly literally
`new Function('return this')` or `new Function('return this;')`
with 
`(() => globalThis)`
outside of SES. But SES itself shouldn't do any of this. It isn't a SES vs JS thing. As your question indicates, it is a strict vs sloppy thing. 

The `(() => globalThis)` will work in both strict and sloppy, so after doing this replacement you should push it upstream as PRs against the sources. And/or use the patches trick that we've been doing, that I think we learned from you.

**Comment by kumavis** [comment]
> it is a strict vs sloppy thing.

its actually a strict vs SES thing as it works in strict mode

**Comment by erights** [comment]
No it doesn't

```js
> new Function('"use strict"; return this;')();
undefined
```

**Comment by kumavis** [comment]
ah, does `Function` put us in sloppy mode again?
below run as a file
```js
"use strict"
console.log(new Function('return this')() === globalThis)
```

**Comment by erights** [comment]
Yes. Caller insensitivity. Like any other function, the meaning of both `Function` and indirect `eval` are not sensitive to the strictness of their caller. That would be dynamic scoping, which is one horror that I have totally succeeded at keeping out of JS!

For both `Function` and indirect `eval`, they evaluate their code sloppy unless that code begins with a `"use strict";` directive. However, SES banishes sloppy mode completely, but still with no caller sensitivity. The SES `Fucntion` and indirect `eval` evaluate their code only `strict`, as if always preceded by a `"use strict";` directive.

**Comment by kumavis** [comment]
thanks :rocket:
