### ISSUE TITLE
Allow correlation of scopeProxy to compartment, as workaround for scopeProxy leakage

### ISSUE THREAD

**Issue by kumavis** [endojs/endo#622]
### update
i realized this proposal is unnecessary, but thread may be informational

### LavaMoat issue summary

LavaMoat needs to be able to support arbitrary platform apis that are this-value specific. eg:
```js
const trueGlobalThis = globalThis
// this, defined in sloppy mode, approximates the behavior of `setTimeout` in chrome
trueGlobalThis.abc = function(){ if (this !== trueGlobalThis) throw new Error("boom")
```

currently it looks like this.
it explodes because abc's this-value is scopeProxy
```js
require('ses/lockdown')
lockdown()
const compartment = new Compartment()
// abc is copied onto compartment.globalThis here
copyEndowmentsToCompartment(policy, trueGlobalThis, compartment.globalThis)
compartment.evaluate('abc()') // < ----- explodes here
```

I'm not sure what non-shim SES's behavior is, but i would expect the this-value to be the `compartment.globalThis`

`copyEndowmentsToCompartment` already wraps functions and getters in order to "unwrap" (membrane-like) the this-value from `compartment.globalThis` to `trueGlobalThis` in order to satisfy the `trueGlobalThis.abc` implementation requirements above and similar requirements found in the wild, especially in chrome (`window.document`, `window.setTimeout`)

we could similarly unwrap the this-value from `scopeProxy` to `compartment.globalThis` if we knew how to verify the `scopeProxy` came from the compartment.
```js
const newThis = compartment.isScopeProxy(thisValue) ? compartment.globalThis : thisValue
```

### proposal
as a workaround for scopeProxy leakage https://github.com/endojs/endo/issues/31,
something like this
```js
Compartment.prototype.isScopeProxy = function (value) { return value === scopeProxy }
```

**Comment by kumavis** [comment]
:bangbang:  actually we can just use the `scopeProxy` leak to get a hold of it and do the check ourselves
of course

**Comment by kumavis** [comment]
mmmm, `scopeProxy` is unique per-evaluation :crying_cat_face:

**Comment by erights** [comment]
> I'm not sure what non-shim SES's behavior is, but i would expect the this-value to be the compartment.globalThis

The proposed behavior would parallel JS's actual behavior for the real first global, the global of the start compartment. The `with` trick is, after all, only trying to emulate the JS semantics of global access, but for a different object as the global. Illustrating JS's global semantics on this issue:

```js
function foo() { "use strict"; return this; }

foo(); // undefined
const x = {};

with(x) { foo(); } // undefined

x.foo = foo;

with(x) { foo() } // x

valueOf() // throws TypeError "Cannot convert undefined or null to object"
```

So, using your `__isKnownScopeProxy__` trick to emulate that behavior would be nice, especially if it is transparent. Doubly good if it is so transparent it cannot be worked around and can enforce the denial of access to the scopeProxy. From your explanation above, it seems the next thing for me to understand is `copyEndowmentsToCompartment`. What does it do? What should it do?

**Comment by erights** [comment]
I updated the code above to insert the relevant comments. The key is the first one. The behavior we will spec, and which therefore we'd ideally like to emulate, is that `this` of a function looked up on the global is `undefined`.
