### ISSUE TITLE
"known security holes"? enumerate? strike?

### ISSUE THREAD

**Issue by dckc** [endojs/endo#628]
in a recent meeting, @kumavis asked about ...

> Still under development: do not use for production systems yet, there are
known security holes that need to be closed.
https://github.com/endojs/endo/blame/master/packages/ses/README.md#L40-L41

The `.domain` issue (#126) seems to be one. Should we cite it from SECURITY.md / README.md / NEWS.md ?

@erights plans to review the situation to see if there are others.

**Comment by dckc** [comment]
see also [security blocker](https://github.com/endojs/endo/issues?q=is%3Aopen+is%3Aissue+label%3A%22security+blocker%22) label

**Comment by kriskowal** [comment]
Addressed in #988
