### ISSUE TITLE
ses-ava is missing a `todo` method

### ISSUE THREAD

**Issue by erights** [endojs/endo#645]
While doing https://github.com/Agoric/agoric-sdk/pull/2733 I discovered that our code uses `test.todo` occasionally but ses-ava does not yet support it.

@FUDCo you wanna?

**Comment by FUDCo** [comment]
Let's close this.

**Comment by erights** [comment]
Close as in "it's already fixed, let's close the bug" or "let's fix this"?

**Comment by FUDCo** [comment]
As in "do we seriously care about this enough to, like, spend time on it?"

**Comment by turadg** [comment]
Closing as a case of the more general problem https://github.com/endojs/endo/issues/647
