### ISSUE TITLE
Node.js util.inspect does not render functions correctly

### ISSUE THREAD

**Issue by danfinlay** [endojs/endo#651]
In a ses-shim compartment, if I use the `require('util').inspect` utility from node.js to print out an object, like `{a: () => {}}`, it will print out that function like an empty object, like `{a: {}}`.

This would be nice to represent as a function.

**Comment by erights** [comment]
Try `assert.quote`. Idiomatically, 
```js
const { quote: q } = assert;

... `${q(thing)}` ...
```

**Comment by danfinlay** [comment]
Got it, thanks!
