### ISSUE TITLE
exclude strings, comments from heuristic eval(), import() checks?

### ISSUE THREAD

**Issue by dckc** [endojs/endo#654]
In trying to run tests on XS, I'm getting bitten by eval() in comments and such. How about removing comments and string literals before looking for eval() and import()?

**Comment by erights** [comment]
Removing how?

**Comment by dckc** [comment]
Regex-based string replace

**Comment by dckc** [comment]
never mind... I guess finding comments and string literals is not straightforward. (in particular, template literals are not regular)
