### ISSUE TITLE
React Native Incompatibility: failed to delete intrinsics.Promise.resolve.prototype (shim)

### ISSUE THREAD

**Issue by EtDu** [endojs/endo#663]
**TLDR: Promise is being polyfilled in a way that is incompatible with SES lockdown**

After ignoring the lockdown source in `babel.config.js` to patch #659 , this is the next error that appears:

```
index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.na…:22304 failed to delete intrinsics.Promise.resolve.prototype TypeError: Cannot delete property 'prototype' of function (value) {
    if (value instanceof _$$_REQUIRE(_dependencyMap[0], "./core.js")) return value;
    if (...<omitted>... }
  at whitelistProperties (index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.na…:102215)
  at isWhitelistPropertyValue (index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.na…:102124)
  at isWhitelistProperty (index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.na…:102163)
  at whitelistProperties (index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.na…:102205)
  at isWhitelistPropertyValue (index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.na…:102124)
  at isWhitelistProperty (index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.na…:102163)
  at whitelistProperties (index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.na…:102205)
  at whitelistIntrinsics (index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.na…:102228)
  at repairIntrinsics (index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.na…:104029)
  at lockdown (index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.na…:104047)

TypeError: Cannot delete property 'prototype' of function (value) {
    if (value instanceof _$$_REQUIRE(_dependencyMap[0], "./core.js")) return value;
    if (...<omitted>... }
```

**Comment by kumavis** [comment]
related to disabling `InitializeCore` via `getModulesRunBeforeMainModule`

**Comment by kumavis** [comment]
may be able to use `processModuleFilter`, but its called after resolution and so ignored module will still have their deps included

**Comment by bentobox19** [comment]
* `resolve` function is added to `Promise` here:
* https://github.com/then/promise/blob/91b7b4cb6ad0cacc1c70560677458fe0aac2fa67/src/es6-extensions.js#L24-L47

```js
// Source: node_modules/promise/lib/e6s-extensions.js
Promise.resolve = function (value) {

// At the Bundle
_$$_REQUIRE(_dependencyMap[0], "./core.js").resolve = function (value) {
```

* `prototype` is a non-configurable property, that's why we cannot delete it:

```js
// Console Query (at the bundle)
Object.getOwnPropertyDescriptor(_$$_REQUIRE(_dependencyMap[0], "./core.js").resolve, 'prototype')

// Response
{value: Object, writable: true, enumerable: false, configurable: false} = $5
```

* See https://262.ecma-international.org/6.0/#sec-function-instances-prototype
* Function instances that can be used as a constructor have a prototype property. Whenever such a function instance is created another ordinary object is also created and is the initial value of the function’s prototype property.
* Which is understood at SES in https://github.com/endojs/endo/blob/7b2b7206d8ed5f6cb0a0abe0026c5426f9cc8651/packages/ses/src/whitelist.js#L230-L238

* To be Continued...

**Comment by bentobox19** [comment]
* Arrow functions don't have a `prototype`!
* https://blog.logrocket.com/anomalies-in-javascript-arrow-functions/

> Arrow functions can never be used as constructor functions. Hence, they can never be invoked with the new keyword. As such, a prototype property does not exist for an arrow function.

* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#use_of_the_new_operator
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#use_of_prototype_property

In a stand alone test with the library by just doing this diff we got the properties at `[length, name]`, without the `prototype` property.

```diff
diff --git a/node_modules/promise/setimmediate/es6-extensions.js b/node_modules/promise/setimmediate/es6-extensions.js
index 24665f5..1a77deb 100644
--- a/node_modules/promise/setimmediate/es6-extensions.js
+++ b/node_modules/promise/setimmediate/es6-extensions.js
@@ -21,7 +21,8 @@ function valuePromise(value) {
   p._W = value;
   return p;
 }
-Promise.resolve = function (value) {
+
+Promise.resolve = (value) => {
   if (value instanceof Promise) return value;

   if (value === null) return NULL;
@@ -58,7 +59,7 @@ var iterableToArray = function (iterable) {
   return Array.prototype.slice.call(iterable);
 }

-Promise.all = function (arr) {
+Promise.all = (arr) => {
   var args = iterableToArray(arr);

   return new Promise(function (resolve, reject) {
@@ -98,7 +99,7 @@ Promise.all = function (arr) {
   });
 };

-Promise.reject = function (value) {
+Promise.reject = (value) => {
   return new Promise(function (resolve, reject) {
     reject(value);
   });
```

The challenge now is convince babel to not transform these arrow functions into Function Instances...

**Comment by bentobox19** [comment]
As this definitely a React Native configuration problem, suggest to close this issue @kriskowal

**Comment by kriskowal** [comment]
Thank you @bentobox19. Looking forward to what happens next.

**Comment by erights** [comment]
Please file a bug with RN and add a link to it to our tracking bug
