### ISSUE TITLE
Trying to understand how SES works.

### ISSUE THREAD

**Issue by AidenRourke** [endojs/endo#680]
I've been trying to test how the underlying object-capability environment works in SES and have run into some confusion.

This is the code I have been experimenting with:

```
const evaluateFactory = Function(`
    with (this) {
        return function() {
            'use strict';
            document; // bar
            this.document; // foo
            (function () { return this.document }());  // error
            window // window!?
        };
    }
`);

const object = {document: "bar"};
const proxy = new Proxy(object, {
    get: function (target, prop) {
        if (prop in target) {
            return target[prop]
        }
        return undefined
    }
});

const evaluate = Reflect.apply(evaluateFactory, proxy, []);
Reflect.apply(evaluate, {document: "foo"}, [])
```

My first bit of confusion is that I don't understand why my Proxy isn't catching the free variable `window`. I expect it to because in the code there's a comment that says "we use 'with' (around a Proxy) to catch all free variable names" .

My second bit of confusion is how in this code:

```
  return FERAL_FUNCTION(`
    with (this) {
      ${optimizer}
      return function() {
        'use strict';
        return eval(arguments[0]);
      };
    }
  `);
```

the call to eval() doesn't have access to all of the website's global variables. I assumed that the eval function given by the Proxy a tamed evaluator but a comment in the code says "when 'eval' is looked up in the proxy, and it's the first time it is looked up after useUnsafeEvaluator is turned on, the proxy returns the eval intrinsic" which implies to me that it is being given the real eval object.

Assuming that the Proxy captures all free variables names, I can see how code executing after `use strict` line in the function returned by `evaluateFactory` cannot access any objects without a direct reference to it passed through the proxy or the `this` value when the function is executed. 

I want to understand this well because I am working on a research paper for school and I want to get this right.

**Comment by AidenRourke** [comment]
I just figured out the first part of my confusion, the proxy object needs to return true for the `has` methods to capture all free variables.

**Comment by erights** [comment]
We are using the real unsafe `eval` function. If we were calling it *as a function*, which is what it looks like, we would indeed be toast. However, by using this syntax combined with this being the genuine unsafe eval function, that syntax is actually the "direct eval" special form, which does the eval in the lexical scope that the special form appears in. Which, in this case, is the `with`.

**Comment by erights** [comment]
An indirect eval with the genuine unsafe `eval` object would also run its code sloppy. By contrast, a direct eval inherits the strictness of its lexical scope.

**Comment by AidenRourke** [comment]
Interesting, so if I were to call `eval` in the `evaluateFactory` function, it would use the scope of the function? If so then everything makes sense.

Still, is there anything I'm missing or is this real "core" of the mechanism?

**Comment by erights** [comment]
I think you got it. If you want to double check, see https://www.youtube.com/watch?v=mSNxsn0pK74&list=PLKr-mvz8uvUg70w0yKGfytaDqxiIBNo_L&index=14&t=799s especially starting at 13:99

**Comment by kriskowal** [comment]
Please reach out to us on our mailing list if there’s more to discuss here! https://groups.google.com/g/ses-strategy
