### ISSUE TITLE
eslint-config: Sync agoric-sdk once and then delete its fork

### ISSUE THREAD

**Issue by kriskowal** [endojs/endo#696]
Currently, powerful globals like `setTimeout` are allowed by default. We should alter the eslint-config such that powerful globals need to be expressly requested with a `/* globals */` jslint comment.

**Comment by dckc** [comment]
ew... we don't share eslint-config between the monorepos? boring.

**Comment by kriskowal** [comment]
The eslint config is identical at the moment. I’m keeping them in sync manually for the moment because changes motivated in one monorepo are hard to vet in the other. We could at any time delete either and receive the other from npm.

**Comment by dckc** [comment]
ok... the endo-copy lacks the March 7 "Make powerful globals explicit" change from agoric-sdk, plus one more about jessie.
https://github.com/Agoric/agoric-sdk/commits/master/packages/eslint-config/eslint-config.json 42bd6e8add36

**Comment by kriskowal** [comment]
> ok... the endo-copy lacks the March 7 "Make powerful globals explicit" change from agoric-sdk, plus one more about jessie.
> https://github.com/Agoric/agoric-sdk/commits/master/packages/eslint-config/eslint-config.json 42bd6e8add36

Thank you for this note. I synced up the repos again, published the endo versions, and will soon have agoric hooked up to the endo versions https://github.com/Agoric/agoric-sdk/pull/3329

**Comment by kriskowal** [comment]
The dapps evidently depend on the versions in the agoric monorepo without expressing a dependency themselves. So, before deleting the agoric variant, I’ll need to also update all the dapps.

**Comment by kriskowal** [comment]
Covered by @michaelfig’s recent work to add Jessie lint.
