### ISSUE TITLE
Upgrade Babel for whitespace bugfix

### ISSUE THREAD

**Issue by kriskowal** [endojs/endo#719]
The current `@agoric/babel-standalone` causes a ladder of indentation for successive comments and creates a header of newlines.

The original `@babel/standalone` contains shims that conflict with SES, so we could attempt to merge upstream in our fork and cut a new release.

It may be possible to migrate to a dependency directly on `@babel/parser`, which we don’t currently use for reasons that may have been lost to the annals of time. It’s likely that it had a conflict with SES. That conflict may no longer apply and having a smaller dependency footprint might make other aspects of the RESM -> SESM migration easier.

**Comment by kriskowal** [comment]
cc @michaelfig 

Plan of record is to update `@agoric/babel-standalone` and continue using it. If we depend upon `@babel/core`, we’ll be pulling in unnecessary powerful and tightly coupled dependencies, unless it has somehow gotten better while we weren’t watching.

**Comment by michaelfig** [comment]
> Plan of record is to update `@agoric/babel-standalone` and continue using it.

I've published a new `@agoric/babel-standalone`.  Ping me again if you need more help.
