### ISSUE TITLE
Add SES sloppy mode detector

### ISSUE THREAD

**Issue by kriskowal** [endojs/endo#740]
SES currently succeeds lockdown under sloppy mode, but warning that it removes `caller` and `arguments` from various of its own functions.

Per #736, this indicates that SES is running in an environment where it cannot enforce its own security invariants.

Write a check at the head of lockdown or SES initialization that detects the presence of one of these properties and explicitly fails with an error and an informative explanation.

**Comment by erights** [comment]
> Write a check at the head of lockdown or SES initialization that detects the presence of one of these properties and explicitly fails with an error and an informative explanation.

Replaying conclusions from an offline chat between @kriskowal and @erights 

The presence of `'caller'` and `'arguments'` is not guaranteed, and so would be a bad sloppy detector. I suggested

`if (function(){return this;}()) {`

but anything will do that is both
   * guaranteed by the language semantics
   * actually reliable on all platforms we care about.
