### ISSUE TITLE
Broken links due to moved packages

### ISSUE THREAD

**Issue by andrey-kuprianov** [endojs/endo#745]
_Surfaced from @informalsystems Agoric Audit of endojs/endo hash f7dcf050ef0fd839ab6500b938791740c9bc702b_

Due to the (recent) moves of several packages, multiple links are broken, or lead to the moved packages. Here are a few examples:

 - In the [@agoric/make-hardener](https://yarnpkg.com/package/@agoric/make-hardener) README, the [SES](https://github.com/Agoric/SES) link leads to the moved package;
 - In the same location, [@agoric/harden package](https://github.com/Agoric/Harden) leads again to the moved package, which says
    > This code has been moved into the packages/harden subdirectory of the monorepo in https://github.com/Agoric/ses-shim . All future development should happen there.
    
    In the above description, the link is incorrect, it redirects to https://github.com/endojs/endo. Also, the path inside this repository is not `packages/harden`, but `packages/make-hardener`.

**Recommendation**: make a walk through the repositories and update the links to reflect the current state.

**Comment by kriskowal** [comment]
Thank you @andrey-kuprianov. Fixed this generally in #810.
