### ISSUE TITLE
Consider revealing globalThis.harden only after lockdown

### ISSUE THREAD

**Issue by kriskowal** [endojs/endo#787]
Currently, we add harden to `globalThis` on initialization, which cannot be used until after `lockdown`. This precludes the possibility of code that can work both with and without SES. We cannot feature-test the environment for a working harden and use it only when it’s available.

**Comment by kriskowal** [comment]
cc @erights I’m thinking it might be better to add `harden` to the environment only after `lockdown`, since this would make it possible for the compartment mapper to be used both inside a compartment (using harden) and outside a compartment (for non-SES cases).

**Comment by erights** [comment]
Why did we decide not to do this previously?

**Comment by kriskowal** [comment]
I don’t recall.

**Comment by erights** [comment]
Ok then, I agree.
