### ISSUE TITLE
Use eshost to run tests in multiple engines

### ISSUE THREAD

**Issue by mhofman** [endojs/endo#812]
https://github.com/bterlson/eshost allows running code in different agents / engines. It would be great to run endo tests in all engines to make sure no implementations exhibit unexpected behavior.

**Comment by mhofman** [comment]
@kriskowal I believe this would be subsumed by moving to test262 and a runner based on eshost?

**Comment by kriskowal** [comment]
Certainly overlaps:
- https://github.com/endojs/endo/issues/870
- https://github.com/endojs/endo/issues/1001

Those issues could be reframed as this one. We need something parody of eshost that runs on every engine with SES shim pre-initialized.

**Comment by kriskowal** [comment]
With https://github.com/endojs/endo/pull/1847 we have a place to stand for adding these tests.
