### ISSUE TITLE
Once-only lockdown

### ISSUE THREAD

**Issue by kriskowal** [endojs/endo#814]
As written, lockdown can be called more than once provided that the lockdown options are monotonically more specific. It turns out with some practice that we aren’t going to need it and that lockdown would be easier to audit if it were simplified to simply reject lockdown after lockdown (and maybe also remove lockdown from the start compartment globalThis).

**Comment by mhofman** [comment]
Currently the function constructor taming tries to be resilient against multiple calls, however this created a security hazard. See #903 

To harden the "no-eval" use case without a breaking change, the taming will be modified to only catch `TypeError`, however once lockdown can only be called once, that `catch` should be removed altogether.
