### ISSUE TITLE
Strict mode optimizer for evaluate

### ISSUE THREAD

**Issue by kriskowal** [endojs/endo#816]
The optimizer currently runs under sloppy mode, and although we doubt that there is any vulnerability introduced just by running the optimizer sloppy, we are much more confident in the semantics of strict mode.  The motivation for having the optimizer in sloppy mode is that it can be reused for multiple evaluations, but in practice we have no such calls.  We could probably both move the optimizer into the inner function and we could also simplify makeEvaluateFactory to simply evaluate.

**Comment by kriskowal** [comment]
We’ve falsified one of the premises in my original description: we now reuse the optimizer for eval and function. There might be in turn a missed opportunity to have a complete finalizer since there might be more mutable properties of globalThis at the time of Function construction.

Regardless, I don’t think this issue blocks Agoric’s Mainnet 1 milestone or really any beyond that, as it is a would be nice comfort blanket for our security invariants.

I’m content to close this out and reöpen if when or if we become ambitious on a weekend. Please correct me if I’m wrong by reöpening this issue.

**Comment by kriskowal** [comment]
@jack-works You make a good point about the non-writable properties of globalThis drifting, though outright replacing the globalThis is not possible.

**Comment by mhofman** [comment]
The optimizer only consider non-configurable non-writable props of `globalThis`. Unless one freezes `globalThis` or explicitly updates the desc of some globalThis props, the default ones would be `undefined`, `NaN` and `Infinity`. When adding shared evaluators, I made sure to delay creation of the evaluator so that the compartment creator would have time to freeze the compartment's global, influencing the optimizer.

**Comment by erights** [comment]
> non-configurable non-writable props

Pedantic nit:

non-configurable non-writable data props

**Comment by mhofman** [comment]
If we ever did this, I believe the following would work:

```js
            (() => {
              'use strict';
              ${globalObjectOptimizer}
              ${globalLexicalOptimizer}
              return function() {
                'use strict';
                return eval(arguments[0]);
              };
            })();
```
