### ISSUE TITLE
Possible bug in allowlist visitor getSubPermit

### ISSUE THREAD

**Issue by kriskowal** [endojs/endo#835]
The function `getSubPermit` could possibly fail to mark a virtualized native function if that case gets overshadowed by preceding case. We need to answer what kind of arrangement in the allowlist and global environment could induce invalid behavior.

```js
  function getSubPermit(obj, permit, prop) {
    const permitProp = prop === '__proto__' ? '--proto--' : prop;
    if (objectHasOwnProperty(permit, permitProp)) {
      return permit[permitProp];
    }

    // TODO maybe above and below should be swapped
    // so that makeVirtualizedNativeFunction gets called in all proper cases

    if (typeof obj === 'function') {
      markVirtualizedNativeFunction(obj);
      if (objectHasOwnProperty(FunctionInstance, permitProp)) {
        return FunctionInstance[permitProp];
      }
    }

    return undefined;
  }
```

**Comment by erights** [comment]
OMG @kriskowal , the bug I found and fixed at https://github.com/endojs/endo/pull/1619 is one you already reported!

In any case, closing as fixed by https://github.com/endojs/endo/pull/1619
