### ISSUE TITLE
SES 0.14.2 incompatibility with Parcel 1

### ISSUE THREAD

**Issue by kriskowal** [endojs/endo#875]
@samsiegart isolated an incompatible interaction between Parcel bundler and SES 0.14.2, where the bundler injects `Object.defineProperty(module.exports, '__esModule', {value: true})`, specifically into the preamble of `commons.js`.

While we encourage developers to inject SES as a script ahead of any modules to avoid passing it through a source-to-source translator that corrupts its intent, we do currently attempt to support bundlers. We have a Parcel integration test that oddly does not reveal this flaw.

The problem is that we capture `Object` off of `globalThis` and reexport the name `Object`, so `Object.defineProperty` in the preamble occurs within a temporal dead-zone for the module scoped constant.

We can mitigate this problem by exporting Object by a different name, like OBJECT, OriginalObject, OG (Objet Genè), Objekt, or Abject.

**Comment by michaelfig** [comment]
I found that `import 'ses/dist/ses.umd.js';` in the usual place (i.e. in the `ui/public/src/main.js`) made things work just fine.  Parcel doesn't mess with the bundle that way.

With just `import 'ses';` Parcel 1 attempts an intrusive rewrite that breaks things.

**Comment by michaelfig** [comment]
As discussed with @kriskowal, the correct solution is probably to rely on SES's built-in bundling, so that the `package.json` `.module` field points to it instead of to the sources.  Then other bundlers presented with just a single file for the `import 'ses'` are less likely to interfere with our particular requirements for how the SES implementation code itself must be bundled.

**Comment by kriskowal** [comment]
Changing `"module":` in `package.json` did not pan out. It caused the integration tests for Parcel, Rollup, &c to fail, with either `.js` or `.cjs` extensions. https://github.com/endojs/endo/pull/880
