### ISSUE TITLE
Ses-ava console virtualization: report to t.log instead of console

### ISSUE THREAD

**Issue by kriskowal** [endojs/endo#891]
SES hides error stacks from callers and reveals them to the global console. SES-ava captures errors thrown in tests and reports them to the console to reveal their stacks, regardless of whether the test passes or fails, generating a great deal of decontextualized noise.

We would like to reveal the error to the test log buffer (t.log) instead. Since SES interacts thru the console API, we would need to virtualize the console for tests.

This console virtualization might be adaptable across other purposes.

**Comment by dckc** [comment]
see also #731

**Comment by dckc** [comment]
#701 is in this direction, yes?

**Comment by kriskowal** [comment]
Yes, very much so.

**Comment by kriskowal** [comment]
To get here, we still need to tease out the compartment shim from `ses`.

**Comment by erights** [comment]
May be fixed by #2109

**Comment by erights** [comment]
Hi @kriskowal , I said in #2109 that it would close this, and so co-assigned myself. But I don't understand your comments about needing compartment work, which #2109 does not do. If #2109 would not close this, please let me know what I'm missing.

**Comment by kriskowal** [comment]
I misunderstood what was necessary to accomplish this. Please disregard.
