### ISSUE TITLE
V8 allows building objects which break invariants

### ISSUE THREAD

**Issue by mhofman** [endojs/endo#901]
One of the JS invariants is that if a check for a property returns non-`writable` and non-`configurable`, then it's observed `value` will always be the same.

@erights discovered in #892 a [bug in v8](https://bugs.chromium.org/p/v8/issues/detail?id=12240) where a module namespace exotic object after a (correctly throwing) `Object.freeze` operation will (incorrectly) claim a property was made non-`writable`. However if that property is representing an export modifiable by the module (such as a `let`), can have its value change, breaking the above invariant.

These exotic objects have a `null` prototype, making them indistinguishable from plain objects.

**Comment by Jack-Works** [comment]
What should be the correct behavior? All instance of the module object becomes frozen?

**Comment by mhofman** [comment]
The behavior specified in the spec is that all the module namespace exotic object properties are writable, and cannot be made non-writable. That would cause `Object.freeze` to throw (which it does), but the properties should not change and `isFrozen` would keep returning false (this is the broken part).

XS actually has a different non-spec behavior, but which I'd consider better than the spec. Only exports which may change (such as `let`) are writable. That means a namespace object with only `const` exports already comes frozen out of the box!

**Comment by mhofman** [comment]
v8 fixed the issue. @erights are we comfortable closing? I don't believe we can reliably detect this case

**Comment by erights** [comment]
Yup. Closing.
