### ISSUE TITLE
SES / endo security policy documentation out of sync with github, hackerone

### ISSUE THREAD

**Issue by dckc** [endojs/endo#920]
https://hackerone.com/agoric?type=team refers to https://github.com/Agoric/ses-shim ; that redirects to https://github.com/endojs/endo , which is good, but SECURITY.md is under packages/ses , so github doesn't treat it as the security policy for the repository.

Also, SECURITY.md doesn't mention hackerone.

cc @jessysaurusrex

**Comment by jessysaurusrex** [comment]
Good catch @dckc! This issue exists in the `agoric-sdk` as well (I caught it Monday), and I set aside some time tomorrow to deal with it.

 @kriskowal suggested a couple of options for closing the gap here, and the one that I like best involves copying the most up to date security.md in use under packages/ses to every package, and keeping them all in sync. This would allow for our disclosure policy to be shipped with the code to NPM as well, which I like for several reasons.  
 
 I will be updating the HackerOne program to make sure that Endo is in scope for submissions to our program. Once that is finished and the copypasta script is in place, I'll come back to close this issue.
