### ISSUE TITLE
Allow extra intrinsic when running lockdown

### ISSUE THREAD

**Issue by Jack-Works** [endojs/endo#925]
![image](https://user-images.githubusercontent.com/5390719/140013683-23baf862-6f6d-4f38-aa5d-4a2fbddb8409.png)

I want to configure my environment to use some new proposals like iterator helpers but lockdown will remove them. Is it possible to specify extra allowed intrinsic when running lockdown?

**Comment by kriskowal** [comment]
The relevant issue to pile on is #318. The idea of record is to separate `repair()` and `lockdown()` such that “shims” can be applied in between those phases, and that we need to reveal some API that allows shims to alter the lockdown permits (currently the “whitelist” in SES source). This specific case might look something like:

```js
repair();
intrinsics.Symbol.asyncDispose = asyncFunctionPermit;
lockdown();
```

Where `repair()` is an preparation step factored out of `lockdown()` that the user can optionally call beforehand, and `intrinsics` is the graph of lockdown permits, exposed so shims can alter them before lockdown.

**Comment by kriskowal** [comment]
@Jack-Works please consider closing this issue as a duplicate and resuming the conversation on #318.
