### ISSUE TITLE
add new ArrayBuffer, Array methods to whitelist?

### ISSUE THREAD

**Issue by dckc** [endojs/endo#937]
In MDN, [Array.prototype.findLastIndex](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/lastIndexOf) seems to be standard. I don't know why we're removing it.

I haven't researched the others. These are new as of a recent XS update.

```
Removing intrinsics.%ArrayBufferPrototype%.maxByteLength
Removing intrinsics.%ArrayBufferPrototype%.resizable
Removing intrinsics.%ArrayBufferPrototype%.resize
Removing intrinsics.%ArrayBufferPrototype%.transfer
Removing intrinsics.%ArrayPrototype%.findLast
Removing intrinsics.%ArrayPrototype%.findLastIndex
Removing intrinsics.%TypedArrayPrototype%.findLast
Removing intrinsics.%TypedArrayPrototype%.findLastIndex
```

**Comment by kriskowal** [comment]
Lockdown only reports that it removed something if it’s not something we’ve explicitly thought about. We mute the warning for things that we know we want to remove.

I’m not sure whether we want to permit `transfer` or `resize`, in particular. We should clearly permit all the others. If we omit `resize`, we should rather tame it and set `resizable` to `false`. My inclination is just to make sure both of those methods are safe and include them. cc @erights

**Comment by mhofman** [comment]
These ArrayBuffer methods are [stage 3](https://github.com/tc39/proposal-resizablearraybuffer). We probably should have a policy regarding inclusion of proposals, but the most sensible is likely to  ignore anything not stage 4.

Regarding what to do regarding  `transfer` and `resize`, I haven't really formed an opinion yet, but at first sight I don't see these operations as providing any more power than expected (they only modify the instance for resize, and also the provided argument for transfer). Regarding resize, we could probably make all instances non-resizable by overriding the constructor to drop the `maximumByteLength` option.

**Comment by dckc** [comment]
> ... We probably should have a policy regarding inclusion of proposals, but the most sensible is likely to ignore anything not stage 4.

@erights said stage 3 in [an Aug 2 comment](https://github.com/endojs/endo/issues/854#issuecomment-891445890).

**Comment by dckc** [comment]
fixed in 824f085095ab56c007eb616143556197e615bcdf

release Coming Soon

**Comment by Jack-Works** [comment]
![image](https://user-images.githubusercontent.com/5390719/156502604-45486f26-529f-4053-bc90-930cd949c2eb.png)

Still left 2 intrinsics

**Comment by erights** [comment]
@Jack-Works , thanks for reporting.

Reopening until these two are added to the whitelist. Perhaps we should also have a consistency check between methods of `Array.prototype` and members of `@@unscopables`

**Comment by erights** [comment]
Closing as fixed by https://github.com/endojs/endo/pull/1618
