### ISSUE TITLE
OOM must fail fast (through unsafe eval switch)

### ISSUE THREAD

**Issue by kriskowal** [endojs/endo#956]
If an attacker can arrange for a stack of a particular depth before calling an evaluator, on a platform with some specific combination of preferential inlining of functions, there is a chance, in the face of maintenance, that a program could cause an evaluator to leak unsafeEval. The implementation as written today, makes a single function call in a finally block to retract the unsafeEval that is temporarily granted to evaluate client code. To eliminate this risk, that finally block should make no function calls and merely reset the underlying flag.

https://github.com/endojs/endo/blob/9a9953bbf80fd4c35d857c999cfe2972f6891912/packages/ses/src/make-safe-evaluator.js#L91

To achieve this, we must integrate the compartment scope handler maker and the evaluator into a shared scope.

And we should leave a comment to the effect that the code in the finally block must never call functions in the future.

**Comment by mhofman** [comment]
Why not revert https://github.com/endojs/endo/pull/833 ?

**Comment by kriskowal** [comment]
Effectively that! It doesn’t revert cleanly, but probably can get it all the way by hand.
