### ISSUE TITLE
SES: Cannot register `lockdown` in new VM context

### ISSUE THREAD

**Issue by ctjlewis** [endojs/endo#986]
Trying to lock down a new context by creating an `isolatedRequire` function:

```js
function isolatedRequire(specifier) {
  const sandbox = createContext({ require, console });
  /**
   * Lock down the component context and then import the module.
   */
  const sesRequire = `
    require('ses');
    lockdown();

    require(${JSON.stringify(specifier)});
  `;
  return runInNewContext(sesRequire, sandbox)
}
```

But it throws:

```
evalmachine.<anonymous>:3
    lockdown();
    ^

ReferenceError: lockdown is not defined
    at evalmachine.<anonymous>:3:5
    at Script.runInContext (node:vm:139:12)
    at Script.runInNewContext (node:vm:144:17)
    at runInNewContext (node:vm:298:38)
```

It works if we `require('ses')` and then pass in the `lockdown` function for the initial context, but that locks down the parent context and kind of invalidates the scoping principle here.

Why won't the `lockdown` identifier register in a new VM context?

**Comment by kriskowal** [comment]
The lockdown function closes over the globals/primordials in the context
it’s initialized in. These are grabbed early in commons.js so that code
that runs between initialization and lockdown is less able to interfere,
though lockdown is still vulnerable to that code in general.

So, SES needs to be evaluated as a program in the other context. SES
distributions can be used as a script or evaluated string in global scope.

We do not intend to support a version of lockdown that must carefully
straddle multiple realms. The current design without a dependency on realms
is a simplification that makes the internal invariants of lockdown
considerably easier to verify.

**Comment by mhofman** [comment]
> ```js
>   const sandbox = createContext({ require, console });
> ```

Wouldn't this cause the `require` of the initial realm to be used? I'm not super familiar with the way node's module loading interacts with realms, but it seems like that setup would not provide the isolation you're looking for. Also, `console` would similarly leak the object graph of your main realm into your new realm.

**Comment by ctjlewis** [comment]
The specific pattern in the specific example I posted is just my best attempt at getting something working.

My goal is to create a context, run the shim, import a module from inside the context, and return it out. I can't get the lockdown identifier to bind though.

**Comment by mhofman** [comment]
What I'm saying is that I don't believe you're loading the ses shim inside the context you created. You're loading it in the parent realm.

**Comment by ctjlewis** [comment]
Gotcha, so require() inside the context binds lockdown to the parent global scope, and that's why lockdown doesn't exist.

Does anyone have any ideas as to how to produce this? We can't require() from inside the isolated context without giving it a reference. Maybe I can emulate it with createRequire()?

**Comment by mhofman** [comment]
Node's `vm` module is pretty barebones. Afaik it doesn't contain any node provided APIs such as `require`, only v8 intrinsics. I highly recommend you don't try to build your own isolation mechanism based on it. You may have better luck with `vm2` or `isolated-vm`.

SES will not on its own load external modules and evaluate them in isolated Compartments. For that you need other parts of Endo. You may instead be interested in [LavaMoat](https://github.com/LavaMoat/LavaMoat) which uses SES/Endo under the hood, and helps you isolate your package dependencies according to policies you define.

**Comment by mhofman** [comment]
@ctjlewis does the above clarify why `lockdown` wasn't available in the context you created? I'll close this issue, but feel free to add a comment if you need further help.
